### ISSUE TITLE
columns in concept lists and regular attributes

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#100]
We have a nice zipfian distribution with the columns with metadata in all concept lists (I paste it below).

I started tagging columns for regularity, currently here:
- https://github.com/clld/concepticon-data/blob/master/concepticondata/data.py#L60

Here are some major types:
- RANK: There are important things, like "rank", which should always be an integer, not float, since rank assumes that we fully resolve the rank of a wordlist (my next PR will correct issues on this).
- LANGUAGES: Furthermore, we have languages, which should be identified as such. I tagged them as "language" in the data.py file above
- SUBLIST: Furthermore, we have sublists, which means that they contain links to other lists, or just an indicator to which it belongs. This is not very systematic at the moment (thaks to the sources).
-  CATEGORY: is actually nice, since it refers to "semantic field" and the like.
- URL: But also XXX_URL (!) refers to links, and this is already automatically handled.

Now, problems are cases like:
- SWADESH_1955_100, etc. where the people link to another concept list by assignign an asterisk or some other symbol or a + and a -, but ideally, we would indicate already when naming the column that this refers to another concept list, so we could write "CONCEPT_LIST_SWADESH_1955_100" or is this an overkill?
- columns like "SCORE", "FREQUENCY", etc. are sometimes composed (AGE_SCORE, SPANISH_FREQUENCY"), sometimes uncomposed, and they usually refer to numerical data (float or int). Is there a way to formalize it or would it also be an overkill?

The general question is: can we regularize some of these aspects without being forced to add json-descriptors?

**Comment by LinguList** [comment]
Here's the current status:

# Common Additional Columns of Concept Lists
* 15 occurences: CHINESE, Wang-2004-100b.tsv, Wang-2006-200.tsv, Lin-2010-89.tsv, Zheng-2007-86.tsv, Allen-2007-500.tsv, Chen-1996-100b.tsv, Hou-2004-180.tsv, SatterthwaitePhillips-2011-423.tsv, Chen-1996-200.tsv, Chen-1996-100a.tsv, Norman-2003-40.tsv, Wang-2004-200.tsv, He-2010-207.tsv, Wang-2004-95.tsv, Wang-2004-100a.tsv
* 13 occurences: RANK, Thomas-1960-168.tsv, Pagel-2007-200.tsv, Pozdniakov-2014-100b.tsv, List-2014-1280.tsv, Tadmor-2009-100.tsv, Pozdniakov-2014-100a.tsv, Kassian-2015-50.tsv, Swadesh-1955-215.tsv, Nicholas-1989-60.tsv, Dyen-1964-154.tsv, Starostin-2007-110.tsv, Haspelmath-2009-1460.tsv, Dyen-1964-196.tsv
* 13 occurences: CATEGORY, Ardila-2007-40.tsv, Thomas-1960-168.tsv, Nahhas-2006-100.tsv, SIL-2002-436.tsv, Zheng-2007-86.tsv, Leibniz-1768-128.tsv, Swadesh-1955-215.tsv, Blust-2008-210.tsv, Urban-2011-160.tsv, Bowern-2011-204.tsv, Bowern-2008-207.tsv, Ferguson-1964-30.tsv, Goddard-2001-42.tsv
* 11 occurences: RUSSIAN, Ardila-2007-40.tsv, Pallas-1786-441.tsv, Key-2015-1310.tsv, Yakhontov-1991-100.tsv, Kassian-2010-116.tsv, Starostin-1991-110.tsv, Starostin-2007-110.tsv, Yakhontov-1991-65.tsv, Yakhontov-1991-35.tsv, Pallas-1789-285.tsv, Dolgopolsky-1964-15.tsv
* 7 occurences: URL, Key-2015-1310.tsv, Ogden-1930-200.tsv, Blust-2008-210.tsv, Dunn-2012-207.tsv, Bulakh-2013-870.tsv, TeilDautrey-2008-430.tsv, Haspelmath-2009-1460.tsv
* 6 occurences: SUBLIST, Yakhontov-1991-100.tsv, SIL-2002-436.tsv, Bennet-1976-100.tsv, SIL-1980-281.tsv, Wang-2004-200.tsv, Wang-2004-100a.tsv
* 6 occurences: SWADESH_1955_100, Trask-1996-207.tsv, Syrjaenen-2013-226.tsv, Mann-2004-209.tsv, Heggarty-2005-150.tsv, Sidwell-2015-200.tsv, Mann-2004-500.tsv
* 6 occurences: SPANISH, Ardila-2007-40.tsv, Key-2015-1310.tsv, Samarin-1967-100.tsv, Huber-1992-374.tsv, Heggarty-2005-150.tsv, Calero-2002-15.tsv
* 5 occurences: FRENCH, Pallas-1786-441.tsv, Key-2015-1310.tsv, Meillet-1921-16.tsv, Samarin-1967-100.tsv, Grollemund-2015-100.tsv
* 4 occurences: GERMAN, Pallas-1786-441.tsv, Samarin-1967-100.tsv, Gabelentz-1891-120.tsv, Gabelentz-1861-24.tsv
* 4 occurences: LATIN, Ardila-2007-40.tsv, Pallas-1786-441.tsv, Leibniz-1768-128.tsv, Pallas-1789-285.tsv
* 4 occurences: STABILITY_SCORE, Thomas-1960-168.tsv, Pozdniakov-2014-100b.tsv, Swadesh-1955-215.tsv, Holman-2008-100.tsv
* 4 occurences: SWADESH_1952_200, Mann-2004-209.tsv, Heggarty-2005-150.tsv, Sidwell-2015-200.tsv, Mann-2004-500.tsv
* 4 occurences: PART_OF_SPEECH, Pagel-2007-200.tsv, Dolch-1936-220.tsv, Haspelmath-2009-1460.tsv, Pagel-2013-23.tsv
* 3 occurences: IDS_ID, Key-2015-1310.tsv, Borin-2015-1532.tsv, Haspelmath-2009-1460.tsv
* 2 occurences: MANN_2004_500, Mann-2004-210.tsv, Mann-2004-209.tsv
* 2 occurences: MITTERHOFER_2013_300, Mitterhofer-2013-353.tsv, Mitterhofer-2013-92.tsv
* 2 occurences: ENGLISH_FREQUENCY, Ardila-2007-40.tsv, Pagel-2007-200.tsv
* 2 occurences: MITTERHOFER_2013_92, Mitterhofer-2013-353.tsv, Mitterhofer-2013-300.tsv
* 2 occurences: COMRIE_1977_207, Janhunan-2008-235.tsv, Syrjaenen-2013-226.tsv
* 2 occurences: SPANISH_FREQUENCY, Ardila-2007-40.tsv, Pagel-2007-200.tsv
* 2 occurences: MATISOFF_1978_200, Mann-2004-210.tsv, Mann-2004-500.tsv
* 2 occurences: CHEN_1996_200, Chen-1996-100b.tsv, Chen-1996-100a.tsv
* 2 occurences: AGE_SCORE, Tadmor-2009-100.tsv, Haspelmath-2009-1460.tsv
* 2 occurences: BASQUE, Ardila-2007-40.tsv, Forni-2013-201.tsv
* 1 occurences: PROPENSITY, Youn-2016-22.tsv
* 1 occurences: SIKUANI, Ardila-2007-40.tsv
* 1 occurences: COGNATE_CLASS_SIZE, Pagel-2013-23.tsv
* 1 occurences: C5, Syrjaenen-2013-226.tsv
* 1 occurences: CATEGORY_1, Gabelentz-1891-120.tsv
* 1 occurences: DESCRIPTION, Haspelmath-2009-1460.tsv
* 1 occurences: CATEGORY_ID, Zheng-2007-86.tsv
* 1 occurences: RUSSIAN_DESCRIPTION, Kassian-2010-116.tsv
* 1 occurences: SUBCODE, Key-2015-1310.tsv
* 1 occurences: PWN_SYNSET, Borin-2015-1532.tsv
* 1 occurences: X, Youn-2016-22.tsv
* 1 occurences: STATUS, Miller-1994-281.tsv
* 1 occurences: ENGLISH_CONTEXT, Kassian-2010-116.tsv
* 1 occurences: ICONICITY, He-2010-207.tsv
* 1 occurences: SEMANTIC_CLASS_ID, Urban-2011-160.tsv
* 1 occurences: RUSSIAN_FREQUENCY, Pagel-2007-200.tsv
* 1 occurences: ANNOTATION, Ringe-2002-333.tsv
* 1 occurences: GREEK_FREQUENCY, Pagel-2007-200.tsv
* 1 occurences: CATEGORY_3, Gabelentz-1891-120.tsv
* 1 occurences: SEMANTIC_CHANGE, Urban-2011-160.tsv
* 1 occurences: COMPOSITE_SCORE, Tadmor-2009-100.tsv
* 1 occurences: C3, Syrjaenen-2013-226.tsv
* 1 occurences: WEIGHTED_DEGREE, List-2014-1280.tsv
* 1 occurences: SUBGRAPH_URL, List-2014-1280.tsv
* 1 occurences: SHAPE, Wichmann-2010-40.tsv
* 1 occurences: PROTOWORLD, Bengtson-1994-27.tsv
* 1 occurences: COMMON_CHINESE, Norman-2003-40.tsv
* 1 occurences: SIMPLICITY_SCORE, Haspelmath-2009-1460.tsv
* 1 occurences: COMMUNITY_ID, List-2014-1280.tsv
* 1 occurences: PWN_POS, Borin-2015-1532.tsv
* 1 occurences: CATEGORY_2, Gabelentz-1891-120.tsv
* 1 occurences: PAGENUMBER, SatterthwaitePhillips-2011-423.tsv
* 1 occurences: PALLAS_1786_441, Pallas-1789-285.tsv
* 1 occurences: EXCLUDED, Bowern-2012-205.tsv
* 1 occurences: HALF_LIFE_1000S_OF_YEARs, Pagel-2013-23.tsv
* 1 occurences: OMW_URL, Borin-2015-1532.tsv
* 1 occurences: SWEDISH, Woll-2010-301.tsv
* 1 occurences: BORROWING_SCORE, Haspelmath-2009-1460.tsv
* 1 occurences: MEAN_RATE, Pagel-2007-200.tsv
* 1 occurences: SEMANTIC_CATEGORY, Janhunan-2008-235.tsv
* 1 occurences: RATE_SD, Pagel-2007-200.tsv
* 1 occurences: CONTEXT, Haspelmath-2009-1460.tsv
* 1 occurences: C1, Syrjaenen-2013-226.tsv
* 1 occurences: SWADESH_GLOSS, Heggarty-2005-150.tsv
* 1 occurences: RUSSIAN_CONTEXT, Kassian-2010-116.tsv
* 1 occurences: SIL_2002_436, Mann-2004-500.tsv
* 1 occurences: SATURATION, Youn-2016-22.tsv
* 1 occurences: NOTE, Beaufils-2015-18.tsv
* 1 occurences: PORTUGUESE, Key-2015-1310.tsv
* 1 occurences: I_E_RATE, Pagel-2013-23.tsv
* 1 occurences: SPANISH_ORDER_OF_DIFFICULTY, Ardila-2007-40.tsv
* 1 occurences: FREQUENCY_OF_USE, Pagel-2013-23.tsv
* 1 occurences: SWADESH_1955_STABILITY_SCORE, Thomas-1960-168.tsv
* 1 occurences: PWN_WORD_SENSE_ID, Borin-2015-1532.tsv
* 1 occurences: SEMANTIC_FIELD, Haspelmath-2009-1460.tsv
* 1 occurences: SUBGRAPH_ID, List-2014-1280.tsv
* 1 occurences: BLUST_2008_210, Luqman-2010-65.tsv
* 1 occurences: IMAGE_URL, Ogden-1930-200.tsv
* 1 occurences: YAKHONTOV_1991_35, Heggarty-2005-150.tsv
* 1 occurences: COMMUNITY_URL, List-2014-1280.tsv
* 1 occurences: REPRESENTATION, Haspelmath-2009-1460.tsv
* 1 occurences: NUMBER_IN_SOURCE, SatterthwaitePhillips-2011-423.tsv
* 1 occurences: DUTCH, Woll-2010-301.tsv
* 1 occurences: S, Wichmann-2010-40.tsv
* 1 occurences: SIL_1980_281, Mann-2004-500.tsv
* 1 occurences: NUMBER_INCORRECT, Nicholas-1989-60.tsv
* 1 occurences: TADMOR_2009_100, Syrjaenen-2013-226.tsv
* 1 occurences: WOLD_ID, Haspelmath-2009-1460.tsv
* 1 occurences: PWN_DEFINITION, Borin-2015-1532.tsv
* 1 occurences: JAPANESE, Lee-2013-200.tsv
* 1 occurences: PROTO_INDO_EUROPEAN, Mallory-2006-100.tsv
* 1 occurences: WIKTIONARY_2003_207, Heggarty-2005-150.tsv
* 1 occurences: C2, Syrjaenen-2013-226.tsv
* 1 occurences: D, Wichmann-2010-40.tsv
* 1 occurences: RELATION, Borin-2015-1532.tsv
* 1 occurences: STATES, Pagel-2007-200.tsv
* 1 occurences: ESPERANTO, Ardila-2007-40.tsv
* 1 occurences: MATCH_QUALITY, Kitchen-2009-95.tsv
* 1 occurences: ANALYZABILITY_SCORE, Tadmor-2009-100.tsv
* 1 occurences: C4, Syrjaenen-2013-226.tsv
* 1 occurences: FREQUENCY, List-2014-1280.tsv
* 1 occurences: REPRESENTATION_SCORE, Tadmor-2009-100.tsv
* 1 occurences: TURKISH, Ardila-2007-40.tsv
* 1 occurences: DEGREE, List-2014-1280.tsv
* 1 occurences: OCCURRENCES, Bulakh-2013-870.tsv
* 1 occurences: SEMANTIC FIELD, Tryon-1983-324.tsv
* 1 occurences: DSS_ID, Bulakh-2013-870.tsv
* 1 occurences: REFLEXES_PER_SYLLABLE_NUMBER, SatterthwaitePhillips-2011-50.tsv
* 1 occurences: BORROWED_SCORE, Tadmor-2009-100.tsv
* 1 occurences: URA100, Syrjaenen-2013-226.tsv
* 1 occurences: ENGLISH_DESCRIPTION, Kassian-2010-116.tsv
* 1 occurences: HAUSA, Kraft-1981-434.tsv
* 1 occurences: COMMUNITY_LABEL, List-2014-1280.tsv
* 1 occurences: PARAGRAPH, Comrie-1977-207.tsv
* 1 occurences: CHAPTER, Key-2015-1310.tsv

**Comment by xrotwang** [comment]
Current status:
```
(concepticon)dlt5502178l:~/venvs/concepticon/concepticon-data$ concepticon attributes
Attribute                       Occurrences
----------------------------  -------------
CHINESE                                  19
CATEGORY                                 14
RANK                                     13
RUSSIAN                                  12
URL                                       7
SUBLIST                                   7
SWADESH_1955_100                          6
SPANISH                                   6
FRENCH                                    5
SWADESH_1952_200                          4
PART_OF_SPEECH                            4
STABILITY_SCORE                           4
LATIN                                     4
GERMAN                                    4
IDS_ID                                    3
MANN_2004_500                             2
SPANISH_FREQUENCY                         2
CHEN_1996_200                             2
AGE_SCORE                                 2
COMRIE_1977_207                           2
BASQUE                                    2
ENGLISH_FREQUENCY                         2
PAGE                                      2
MITTERHOFER_2013_92                       2
MATISOFF_1978_200                         2
CATEGORY_ID                               2
MITTERHOFER_2013_300                      2
SWEDISH                                   1
PWN_SYNSET                                1
REFLEXES_PER_SYLLABLE_NUMBER              1
SATURATION                                1
DUTCH                                     1
PALLAS_1786_441                           1
SEMANTIC_CATEGORY                         1
SUBGRAPH_URL                              1
PROTOWORLD                                1
REPRESENTATION                            1
ESPERANTO                                 1
OCCURRENCES                               1
D                                         1
PWN_DEFINITION                            1
CATEGORY_3                                1
CATEGORY_2                                1
CATEGORY_1                                1
PAGENUMBER                                1
X                                         1
MEAN_RATE                                 1
CIHUI_ID                                  1
FREQUENCY                                 1
COMPOSITE_SCORE                           1
COMMUNITY_URL                             1
BORROWED_SCORE                            1
SEMANTIC_CLASS_ID                         1
CHAPTER                                   1
PROTO_INDO_EUROPEAN                       1
SUBGRAPH_ID                               1
RUSSIAN_CONTEXT                           1
CONTEXT                                   1
SWADESH_1955_STABILITY_SCORE              1
SEMANTIC_FIELD                            1
WOLD_ID                                   1
GREEK_FREQUENCY                           1
RUSSIAN_DESCRIPTION                       1
SIKUANI                                   1
HALF_LIFE_1000S_OF_YEARs                  1
S                                         1
PARAGRAPH                                 1
ICONICITY                                 1
BLUST_2008_210                            1
ANNOTATION                                1
REFLEX_MEANINGS                           1
ANALYZABILITY_SCORE                       1
COMMON_CHINESE                            1
COMMUNITY_ID                              1
SEMANTIC FIELD                            1
ENGLISH_CONTEXT                           1
EXCLUDED                                  1
I_E_RATE                                  1
SEMANTIC_CHANGE                           1
ENGLISH_DESCRIPTION                       1
RATE_SD                                   1
REPRESENTATION_SCORE                      1
WEIGHTED_DEGREE                           1
NUMBER_INCORRECT                          1
PWN_WORD_SENSE_ID                         1
SIMPLICITY_SCORE                          1
WIKTIONARY_2003_207                       1
MATCH_QUALITY                             1
SHAPE                                     1
COMMUNITY_LABEL                           1
C3                                        1
C2                                        1
C1                                        1
HAUSA                                     1
C5                                        1
C4                                        1
PORTUGUESE                                1
SIL_1980_281                              1
JAPANESE                                  1
SPANISH_ORDER_OF_DIFFICULTY               1
SUBCODE                                   1
SIL_2002_436                              1
RUSSIAN_FREQUENCY                         1
WANG_2006_200                             1
YAKHONTOV_1991_35                         1
PROPENSITY                                1
DSS_ID                                    1
DEGREE                                    1
TURKISH                                   1
BORROWING_SCORE                           1
COGNATE_CLASS_SIZE                        1
STATES                                    1
PWN_POS                                   1
FREQUENCY_OF_USE                          1
TADMOR_2009_100                           1
IMAGE_URL                                 1
ENGLISH_1                                 1
STATUS                                    1
SWADESH_GLOSS                             1
SWADESH_ID                                1
RELATION                                  1
OMW_URL                                   1
DESCRIPTION                               1
NOTE                                      1
NUMBER_IN_SOURCE                          1
URA100                                    1
```

**Comment by LinguList** [comment]
Freaky Zipfian distributions. Cases like "URA100" annoy me, but it is not necessarily straightforward to integrate the judgments the authors make regarding subsets of their lists into our intersections and unions. I adopted one policy to re-write those links if we have the lists by naming the column TADMOR_2009_100 if the content says that item Author-Year-ListLength-ID links to the list of Tadmor-2009-100, and usually, the column only contains a checkmark, as this is what I get from the data, but I think starting by trying to actually provide real links would be too much of work (and involve disagreement), as well as it would be difficult to handle regularly, as authors sometimes provide glosses (Mann-2004-500), sometimes not (Uralex-List, I think it's Syrjaenen-???), etc. But maybe we could think of adding column-information in the metadata? Like "x" is an URL, or do we actually need it? I have definitely tried to describe all major column content in the note-field of the metadata-table.

**Comment by LinguList** [comment]
Ah, I forgot:

Score, Frequency, Number, and URL as suffix are rather consistently used. And I could easily provide the links to other concept lists if they have the formula Author_Year_Items, as in Tadmor_2009_100, so by tagging these column names, one could at least reduce variation.

**Comment by xrotwang** [comment]
I think, adding JSON metadata to describe additional columns is the way to go. It's just flexible and non-intrusive, i.e. does not require changing the data. So I see the following ways to address the issues you mention:
- *RANK should be integer*: Add a `datatype` specification.
- *LANGUAGES*: Add a [`propertyUrl`](http://w3c.github.io/csvw/metadata/#cell-propertyUrl) pointing to the languoid on Glottolog.
- *URL, XXX_URL*: Add a `datatype` specification.
- *SUBLIST*: Add a [`valueUrl`](http://w3c.github.io/csvw/metadata/#cell-valueUrl) property, resolving the column content to (possibly multiple) identifiers of concepts in other lists.

So I wouldn't want to regularize the data avoiding JSON descriptors, but instead use the JSON description as a first in-obtrusive step towards regularization. In particular for lists that may be curated by their owners within concepticon-data, this would be a good mechanism, I think. As a first step, I could create metadata stubs for all concept lists, and we could then open issues for all cases that require editing the metadata.

**Comment by xrotwang** [comment]
Even for the worst case scenario, the JSON metadata approach would at least give us a good place for a description of everything we know about a column (e.g. using a [common property `dc:description`](http://w3c.github.io/csvw/metadata/#common-properties)).

**Comment by xrotwang** [comment]
Of course, once we have per-conceptlist metadata files, these could be used to replace `conceptlists.tsv` ...

**Comment by LinguList** [comment]
Yes, I agree. Here's a question that came just up in my mind: I often use some kind of a prefix, like ```_id``` or ```_rank``` or ```_score``` to indicate certain column data-types. Especially ```_score``` and ```_rank``` should be captured a lot. So here's my question: can we handle this as well in terms of JSON meta-data description or is it in conflict with specifications?

**Comment by xrotwang** [comment]
I think we could use this info when initially (automatically) creating the metadata stubs. But after this, the information about the datatype will be explicit (and could even survive a column renaming).

**Comment by LinguList** [comment]
Okay, so no hope to make this an application that would be read in, detected the suffix (not the prefix, sorry), and determining the datatype? That's what I somehow use by now to allow for multiple cognate sets in a flat file: EDICTOR searches for ```_ID``` columns and sets their data-type to integer. The advantage -- but this is not about concepticon, more about cldf-wordlists -- is that one can have different cognate sets etc. in the same file. But I understand that in terms of interpretation this is a bit messy.

**Comment by xrotwang** [comment]
Well, EDICTOR is javascript, no? So reading a JSON metadata file that describes a table would be trivial. But turning the column name into some sort of specification doesn't look ok to me.

**Comment by xrotwang** [comment]
I can see that ideally, one would like to have something simpler than implementing the whole Tabular Metadata spec. But my experience in the last couple of weeks was that a big enough chunk of this spec is **actually useful** for us, so we better bite the bullet and go all the way, than re-inventing it step-by-step.

**Comment by xrotwang** [comment]
The simple fact, that I can link to relevant parts of the spec whenever needed, is already quite a bit better than
- having to come up with documentation yourself
- putting this documentation somewhere where it can be linked and found

**Comment by xrotwang** [comment]
So in the case of EDICTOR, being able to point to the spec and say: "This is how you make EDICTOR aware of typed data" seems like a win.

**Comment by LinguList** [comment]
I agree. And I was anyway thinking recently of making exactly this: allowing EDICTOR to READ some metadata to also know the current configuration. And since by now, as I understand, one can even use internal separators, this would solve the problem of those ugly lambda-things I write in the conf-files in lingpy.

**Comment by xrotwang** [comment]
Exactly, being able to specify
- second-level separators per column
- datatypes (which will be applied to each item in a multivalued cell)
- CSV dialects

goes a long way.

**Comment by xrotwang** [comment]
Ok, so I'll go ahead and add table descriptions for all concept lists, possibly using a generic fallback for the ones that only have the minimally required columns, and then close this issue.

**Comment by LinguList** [comment]
Excellent!
