### ISSUE TITLE
Concepticon Website: new logo and new favicon

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#106]
I propose, but this can be discussed, a new logo (only slightly modified) and a new favicon.

Here's the new logo:

![new-logo](https://cloud.githubusercontent.com/assets/2916210/14134965/c686f994-f65a-11e5-96f0-c32408be8f06.png)

Here's the favicon:

![new-favicon](https://cloud.githubusercontent.com/assets/2916210/14134966/c687d8be-f65a-11e5-80be-ebf065633f0c.png)

It's actually only a bad joke, but due to the similarity between the name of the "concepticon" and the "decepticons" in [transformers](https://en.wikipedia.org/wiki/Decepticon), I thought it was funny to make an allusion to their insignia:

![insignia](https://upload.wikimedia.org/wikipedia/en/9/95/Decepticon_small.jpg) in the favicon. But I would not insist on this, since it is obviously just a bad joke.

**Comment by cysouw** [comment]
I like bad jokes :-)

best
m.

————————
Michael Cysouw

Auerfeldstrasse 20
D-81541 München

home: +49 (0) 89 4805 8805
mobile: +49 (0) 160 94 777 076
email: cysouw@mac.com
web: www.cysouw.de/home
————————

**Comment by SimonGreenhill** [comment]
surely there's a pun about 'concept icon' somehow?

**Comment by LinguList** [comment]
Actually, concept-icons is what you find when you google the
"concepticon" at the moment...

**Comment by xrotwang** [comment]
@LinguList should be opened as issue on clld/concepticon

**Comment by LinguList** [comment]
I see, should I also move some of the other issues, like #105 ?

**Comment by LinguList** [comment]
Just linked it and closing it for now.
