### ISSUE TITLE
Release Policy: Allow for intermediate releases which do not appear in the Web-App?

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#121]
I was thinking, that we should decide on some release policy:

1. once  a year, we update the data with a new release (fully numerical, like 1.0, 2.0, or point, like 1.1, etc.?), this is clear and obvious
2. in the meantime, we might, however, want to make smaller releases if new data is linked and actively used in certain contexts, here we do not need to re-launch the web-app, but we might want to release the data officially via github/zenodo, and we could include a pointer on the README (they now also have pointers for "latest doi" in Zenodo

But this does actually not need to be decide right now, but in the course of development during the next year, after official launch of v1.0 in the web-app.

**Comment by xrotwang** [comment]
I think if these minor releases don't happen more often than - say - every three months, I'd also push them to concepticon.clld.org. And I'd use [semantic versioning](http://semver.org/) for the app, too, i.e. new major versions may break backwards compatibility.

**Comment by LinguList** [comment]
Ah, I see. I don't assume that we will have changes like 1.1, 1.2 more often than every three months, and if we use patches, like 1.1.1 also for those cases where, say, we have a publication which makes use of a specific state, which is not yet a real minor change, but potentially contains a new concept list, maybe even provided by somebody else, we would have the flexibility and the continuity in good balance. 

BTW: I think we should follow the same principle of semantic versioning also in lingpy.
