### ISSUE TITLE
list of contributors to keep track of those who helped

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#128]
in order to avoid that we forget who contributed what, we should make an explicit list of contributors, or establish some explicit way to handle this. One could classify contributions to a simple schema (scan, typed-off text, links, other), and list the names with a data of contribution, or the name and for each contribution tracking type and date, potentially also the list that was contributed.

For the moment, it may even be a simple text-file, yet it seems that we should not forget about this in the future to avoid that we forget those whom we should thank.

**Comment by xrotwang** [comment]
Along the lines of this: https://github.com/Pylons/pyramid/blob/master/CONTRIBUTORS.txt ?

**Comment by LinguList** [comment]
Yep, but we need to keep in mind that we will have also contributions from people who are not on github. And we'll have contributions, like full scans, which we can mention, but not show and publish.
