### ISSUE TITLE
Missing russian translation in Kassian 2010

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#136]
There are two cases of missing russian concept labels in [Kassian 2010](https://github.com/clld/concepticon-data/blob/62d947e10420539b055fdbdc89f5aadfadb750c9/concepticondata/conceptlists/Kassian-2010-116.tsv#L32). Currently this leads to errors in the concepticon app. Is this a bug we should fix in the data or cope with missing data in the app?

**Comment by LinguList** [comment]
it's an error, I just corrected it (see attached file), or should I push?

[Kassian-2010-116.tsv.zip](https://github.com/clld/concepticon-data/files/256634/Kassian-2010-116.tsv.zip)

**Comment by xrotwang** [comment]
i'll include it in the pr

**Comment by xrotwang** [comment]
So should we consider missing translations always a bug? Just encountered another concept list missing french translations.

**Comment by LinguList** [comment]
which one? It may well be that we receive an original list which lacks
translations, and this should surely be no bug. Yet maybe, in the tests,
there should be a warning.

**Comment by xrotwang** [comment]
three french translations missing in Pallas 1786.

**Comment by xrotwang** [comment]
e.g. https://github.com/clld/concepticon-data/blob/62d947e10420539b055fdbdc89f5aadfadb750c9/concepticondata/conceptlists/Pallas-1786-441.tsv#L370

**Comment by LinguList** [comment]
all right, compared with the source: this is the case, they are missing.

BUT: we have more missing translations there, also German ones, but they
are indicated by a dash. So either all dashes should be removed, or we
could say that dashes indicate explicit absence in source (or another
symbol), since this is definitely the case here...

**Comment by xrotwang** [comment]
ok, since the dash is already there, we could settle on this symbol to explicitly mark missing data in the source. Although maybe something like `NA` may be more transparent.

**Comment by LinguList** [comment]
NA could be confused with real data (although its unlikely to happen),
but I tend to use a gap, and it is well possible, that I used it in
other cases as well. Otherwise, the Ø symbol is something that linguists
would like, but sticking with the dash would be easier for now.

**Comment by xrotwang** [comment]
Ok, one more missing: ERROR:Janhunan-2008-235.tsv:224: missing source language translation ENGLISH

**Comment by LinguList** [comment]
should be "one". The source was having combined cells, which was
difficult to read, and there, I apparently forgot it when typing the
data off...

**Comment by xrotwang** [comment]
Ok, it seems `-` is often used to signal missing data, e.g. http://concepticon.clld.org/values/Heggarty-2005-150-134
Should we generally disregard these values upon import in the DB? I think this would make sense.

**Comment by LinguList** [comment]
so that the respective  is not shown in the list view? I agree. There's
only one point, I also realized yesterday, and I wanted to ask you: if I
understand correctly, unlinked parts of lists are currently not
imported, right? Yet if possible, it would be good to have also the
unlinked stuff when looking at a concept list. Otehrwise it is quite
confusion to see a list with officiall 60 items, which is then only
represented by 58 items, etc.

**Comment by xrotwang** [comment]
I agree, but will have to check in how many places an assumption about a linked ConceptSet being present is made.

**Comment by xrotwang** [comment]
Hm. This is non-trivial to implement. The easiest alternative would be a special `<NA>` ConceptSet. While this would be a bit weird and require special handling when re-using the concepticon data, it would probably also make some sense, because listing all unmapped concepts on the details page of the `<NA>` ConceptSet may be interesting.

**Comment by LinguList** [comment]
this was actually also the same what I was just thinking, and it would
be definitely interesting, and potentially also help for debugging, when
with time new simialr concepts for strange stuff emerge and we decide to
come up with a new official concept set...

**Comment by xrotwang** [comment]
It's also a question whether this is something we could sneak into a 1.0.2 release. It could be argued to be a bug of the web app to not list all data present in the data repos, though.

**Comment by LinguList** [comment]
yep, if it's not too complicated to realize, I'd argue for the bug, since it raises surprise when looking at the data...
