### ISSUE TITLE
Provide mapping to babelnet, where possible

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#15]
[Babelnet](http://babelnet.org) is a very nice resource that defines its own synsets and maps them to omegawiki, princeton wordnet, multwordnet, and wikipedia. We should try to map our concepts to it, where possible. I am currently preparing an automatic pre-mapping using their API. It is probable that we will have unmappable items, but if we could provide some coverage of about 80% (which seems realistic), it would be very nice. To test babelnet, check out the [babelfy](http://babelfy.org) website, where one can just insert words and see which synsets they infer for them.

If the mapping can be provided to, say, 80% of our concepts, we can delete the omegawiki-links, since they should be included in babelnet (and it is unlikely we are able to add more than the ones we already have, given that the api of omegawiki is working so slowly...).

**Comment by xrotwang** [comment]
Yes, it looks as if Babelnet could replace omegawiki, at least as a provider of further links and definitions. It may not be editable right away, but as far as I understood, that aspect of omegawiki wasn't as important as initially expected, right? Babelnet may even be interested in aggregating our data. Do you know any of the people involved in the project?

**Comment by LinguList** [comment]
Yes, OmegaWiki is problematic to edit, and it also takes a lot of
manpower to maintain the stuff (and the interface is very slow).

I don't know the people of Babelnet, but we might consider contacting
them. It seems that we may really be able to provide some interesting
data, albeit for very specific purposes.

I run a script to compare Babelnet to our current status of the
concepticon, but this has yet to be reviewed, and I am facing some
issues in finding the time to pursue all I would like to pursue...

**Comment by LinguList** [comment]
Well, having looked into this for some time now, I am still in favor of planning to have babelnet links for the concepticon, but we need a Hilfskraft to support us here, since it's a rather tedious work.

**Comment by LinguList** [comment]
It is possible to map to babelnet in a rather straightforward way (with some loss of accuracy, since they sometimes have strange definitions). For the milestone for 1.0, I think we would be good with having 500 concept sets mapped (currently, I'm at about 220). More might be feasible, but possibly not worth the pain. It is rather for illustrating at this stage that we can and want to add additional data to our concept sets, especially in those cases where it would be impossible to add the data as another concept list.

**Comment by LinguList** [comment]
Update: it's about 330 concepts that are sufficiently mapped now.
