### ISSUE TITLE
rename python lib to pyconcepticon

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#153]
In analogy to the way data can be accessed from programmatically in the [Glottolog data repository](https://github.com/clld/glottolog), we should provide access to concepticon data via a client API in a package `pyconcepticon`, distributed with the repos.

**Comment by SimonGreenhill** [comment]
concepyicon!

**Comment by xrotwang** [comment]
@SimonGreenhill  I have a hard time typing concepticon correctly as it is. Dunno if this will get worse with your suggestion :)
