### ISSUE TITLE
Add duals

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/concepticon-data#166]
e.g. 
we(dl.ex.)	
we(dl.in.)
	you(dl)
	they(dl)

**Comment by LinguList** [comment]
do we have any list that requires these? It is usually best to start from lists actually making the difference, so that it's easier to jump on to it, i.e., to justify establishing a new concept set. If it's, for example, the parabank list, it would be good to link its core in a rush (sibling terms are now mostly there), but we need both the list and a way to cite it.

**Comment by SimonGreenhill** [comment]
Working on one now by Smythe/Z’ggragen. What’s the best practice here — add a pull req. with these items marked as NA?

**Comment by LinguList** [comment]
> Working on one now by Smythe/Z’ggragen. What’s the best practice here —
> add a pull req. with these items marked as NA?

ideally, you could add them to the end of the list concepticon.tsv in concepticondata/

adding a definition is as straightforward as "first person refering to two people" etc., numbers are added consecutively, but if you leave places empty, we can also add those missing definitions afterwards. 

BTW, just figured we already have YOU TWO (see ID 2111).

You could go for (tab-separated):
```text
2633	WE TWO	Kinship	The speaker or writer and at exactly one other person.	Other
2634	THEY TWO	Kinship	The third person dual of the personal pronoun.	Other
2635	WE TWO (INCLUSIVE)	Kinship	The speaker or writer and at exactly one other person.	Other
2636	WE TWO (EXCLUSIVE)	Kinship	exclusive “we”: I and exactly one other person, but not the addressed person (you)	Other
2637	WE TWO (INCLUSIVE)	Kinship	inclusive “we”: I and exactly one other person, including the addressed person	Other
```
Adding relations (we inclusive, exclusive) might also make sense, but I can take care of that afterwards, and I suggest we just leave this issue open until this is done.

**Comment by LinguList** [comment]
Otherwise, let me know which concepts you need, and I'll add them and push them quickly before, so you're free to map.

**Comment by SimonGreenhill** [comment]
Cool -- can you add those please, I'll let you know when I come across them (btw: should 2635 just be "We two"?)

**Comment by LinguList** [comment]
Here, I'd say we follow the current ordering for "we", where we have "we", meaning unspecified target, and in-/exclusive specifying the targets. From what I understand, we vs we-inclusive is what we find in some Chinese dialects (including Beijing Mandarin, although it's disappearing). Or did you mean that it should be "we two" for another reason?
