### ISSUE TITLE
concepticon 1.1 before lexibank launch

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#178]
I think it would make sense to go for [concepticon 1.1](https://github.com/clld/concepticon-data/milestone/3) before launching lexibank.

**Comment by LinguList** [comment]
Yes, I agree, and maybe, ideally, we could add as many of the missing lists in lexibank in this launch, requiring, say, some minimum of coverage which would say that either 80% of the distinct concept of a dataset are linked, or 200 words, if the dataset is large.

**Comment by xrotwang** [comment]
Maybe a better cut-off in terms of coverage would be "any concept with counterparts in more than one (two?) language must be mapped".

**Comment by LinguList** [comment]
also possible, but it should be just possible to define a lower bound of concepts to be mapped (rule of thumb of 200 is important for phylo-studies and automatic cognates), if the concept list is too long (more than 300 concepts), as without more human resources, we won't be able to map lists like TNG and others completely. But making a priority list based on reflexes of concepts in the data is a good idea.

**Comment by xrotwang** [comment]
we're on the way
