### ISSUE TITLE
Missing translations in Pallas-1786-441

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#183]
In Pallas-1786-441 we have 5 occurrences of `-` for a translation of a concept, in addition to a couple of `?`.
Can we - and do we want to - fix this?

**Comment by LinguList** [comment]
nope, the "-" are missing in the original source, the "?", I don't know, but will check...

**Comment by LinguList** [comment]
okay, we have "?" and "-" which mean the same, so we should only use one. However, as said before: "-" and "" is not the same, as this is an explicitly missing translation in the source, which should be indicated.

We used "ß" to indicate the German letter whcih looks like an "f" but means a "s" in ancient texts. Maybe, replacing it by "s" would also be straightforward, as it is just orthographical (and regular). But I don't really know what a meaningful digitization would require.
