### ISSUE TITLE
check author names in bibliography

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#184]
our "compilers" have duplicates, like Atkinson, Quentin D. vs. Atkinson, Quentin. These should be checked and modified before next launch.

**Comment by xrotwang** [comment]
Hm. But we don't really parse the authors into individual persons, do we? Deduplication of authors is a hard problem, in general - people marry, change names, etc. Do we really want to identify individual persons and their contributions?

**Comment by LinguList** [comment]
Nope, I just wanted to make sure to avoid these things that look sloppy, like, e.g., writing one time William Wang, and the other time William S.-Y. Wang, and then even another time only Chinese Wáng Shìyuán, as this gives users the impression as if we did not really care about the sources. And the errors I mentioned were due to sloppyiness (from my side) in the bibtex...

**Comment by xrotwang** [comment]
Ok. I'll leave it to you to decide when you cleaned up sufficiently :)

**Comment by LinguList** [comment]
Maybe, at some point, I'll just close this issue completely frustrated ;-)

**Comment by xrotwang** [comment]
So should this issue be an eternal reminder? If so, we shouldn't tie it to a milestone :)

**Comment by LinguList** [comment]
well, I just went through the bibliography and think it is mostly fine for now, although not all authors have full names so far. I think we can close it with my next PR, and then I'll just try to insist that I mysefl and all contributors are more strict with bibliographies.

**Comment by LinguList** [comment]
Evgeniya Korovina sent me a complete list of proposed corrections. This should be checked against our author names, as it is possible that there are still some errors left, and the list also fixes the author names in conceptlists.tsv, which is of course, also nice to be fixed.

**Comment by LinguList** [comment]
[ConcepticonCompilers.txt](https://github.com/clld/concepticon-data/files/1531008/ConcepticonCompilers.txt)

**Comment by LinguList** [comment]
This should also be added to the "RELEASING.MD"

**Comment by SimonGreenhill** [comment]
Might be worth trying something like https://nameparser.readthedocs.io/ ?

**Comment by LinguList** [comment]
cool, the major problem we have, however, are Chinese names, and I assume, they are not covered?

**Comment by SimonGreenhill** [comment]
No, only English :/

**Comment by xrotwang** [comment]
I'm working on this right now.

**Comment by xrotwang** [comment]
Hm. Turns out our `Bennet, P.R.` is actually [`Bennett, Patrick R.`](http://worldcat.org/identities/lccn-n87130600/). Change the relevant identifiers of lists and concepts?

**Comment by LinguList** [comment]
I guess we'll have to...
