### ISSUE TITLE
Helper scripts update

### ISSUE THREAD

**Issue by evoling** [clld/concepticon-data#189]
Some of the helper scripts are out of date. For example, maplist.py tries to use e.g. `from concepticondata import *` when the current structure of the package calls for `from pyconcepticon.data import *`. You can see [my fixed version of the maplist.py](https://github.com/evoling/concepticon-data/blob/helper_updates/helpers/maplist.py) script in my fork of concepticon-data.

If you would like I can fix the other scripts in this directory as well and submit a pull request.

**Comment by xrotwang** [comment]
Thanks! I rearranged the package layout at some point to be more in line with other repositories (lexibank-data, glottolog, ...). So I hope this will have been the last breaking change.

**Comment by LinguList** [comment]
so this only now: the helper scripts are all completely outdated and were mainly used by myself to link the list, although some of them do some good work.  Not all are actually needed, and a complete re-arrangement would be useful, also in terms of functionality (GLOSS vs. ENGLISH in maplist.py, etc.). While the fix for maplist is important, I guess instead of fixing the other scripts, we should try and include them in the API. Imagine

```shell
$ concepticon maplist INPUT.tsv > OUTPUT.tsv
```

Wouldn't that be convenient?

**Comment by Anaphory** [comment]
If those helpers will become full command line tools (as suggested above), it may (in addition to paths relative to some known base directory, as mentioned in #200) also be worth handing command line argument parsing to `argparse`, to get more helpful error messages.

**Comment by xrotwang** [comment]
I'll take a stab at refactoring the helper scripts. @LinguList which ones should we keep and which ones throw out?

**Comment by LinguList** [comment]
For the moment, stopped using any of them, but the "rerefine" was crucial and saved a lot of time, as it resolved the sameas-relations by creating a network, using the concepticon_id as the basic, and adding or modifying concepticon_gloss from this, also selecting the lowest ID for a cluster of same-asses. 

Another script involved testing the hierarchies, to avoid that they fail, and having a test here (only use specific relations, test for same gloss and same ID, refine if gloss is different from ID by replacing gloss with new gloss in concepticon.tsv. As we may change gloss names but usually keep ids, it seems crucial for me to have some checks, and automatic corrections, as this saves a lot of work.

All the rest is obsolete by now, I'd say.
