### ISSUE TITLE
Mapping of HIDE, HIDE (ONESELF), HIDE (SOMETHING) should be checked

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#191]
The TBL List (Huang-1992-18XX) contains a distinction for hide (oneself) and hide (something). So we should add those concepts and review existing instances, whether they rather belong to the more specified categories.

**Comment by LinguList** [comment]
Just for the record: ID in TBL data is: 1169 and 1295

**Comment by Schweikhard** [comment]
We have those concepts. The mappings might need to be checked, though.

**Comment by Schweikhard** [comment]
In List2016 it says 躱 to hide (conceal).
The Chinese points to HIDE (ONESELF), the English to HIDE (SOMETHING).
Which is more reliably here?

**Comment by LinguList** [comment]
The list is originally in Chinese, and the translation and concepticon linking was made by myself. It is supposed to be directly derived from cihui, so the English entry should be in sync with Cihui (Beijing Daxue 905), and this follows hide (oneself).
