### ISSUE TITLE
Could pyconcepticon include the data?

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/concepticon-data#194]
Perhaps the data could be packaged with the pyconcepticon package. This would mean that users could rely on having the wordlist data installed and not have to remember e.g. to use the `--concepticon-repos` flag in e.g. https://github.com/glottobank/lexibank-data.

On the other hand this does increase the size of the package -- ~3.5mb  if you ignore the `source` directory.

**Comment by LinguList** [comment]
I'd favor packaging everything together. At the moment, does this work by installing in develop mode? It will just require to add a MANIFEST to setup, and it would also facilitate to use pyconcepticon in lingpy in future versions.

**Comment by LinguList** [comment]
Alternatively, one could think of creating some easy-to-store-dump of the data, so that one does not need to read in tsv-files (maybe a minified json, produced upon installation or upon upgrades). This would in my opinion also be useful for glottolog, as it currently does not yet read all files in py3 (takes ages to go through all inis).

**Comment by xrotwang** [comment]
I think while this may make things easier for a user, it does increase complexity and maintenance cost for the maintainers considerably. Actually, I'd argue that even for the user, this comes at a cost:
- increased package size
- no simple way to work on a new concept list and new lexibank dataset in parallel (which I guess would be a common use case). The same applies to the glottolog data.

On the other hand, there are a few simple options to make the setup for a user easier:
- If `clld/concepticon-data` is cloned locally and `pyconcepticon` installed via `python setup.py develop`, the repository location should be "known" to the concepticon API object, thus no need to use `--concepticon-repos`. I think this should be recommended as the standard setup.
- simply aliasing the `lexibank` command including the flags.

**Comment by xrotwang** [comment]
I hope to have enough time next week to document working on concepticon as well as lexibank a bit better. And if that's done, I'd vote for closing this issue.

**Comment by LinguList** [comment]
Agreed. I started preparing some Notebook-files that also document what I personally do on lexibank or lingpy etc., as I keep forgetting it (also usage of clldutils, etc.). Maybe that's the main thing we need: some more recipes in our cookbooks...

**Comment by xrotwang** [comment]
I'm closing this, because the standard way of using pyconcepticon should be together with either
- a clone of concepticon-data
- or a release of concepticon-data
