### ISSUE TITLE
Discussing Contributor's Policy for the Concepticon

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#199]
When people do explicit concept list mapping and load their lists into the concepticon using PRs that help us expand it, we should have a policy of when we include new people in the list of official authors/editors.

I'd see two possibilities: 

* If we aim for a publication cycle of one year, as in other projects, we decide on the authors on board on a yearly basis. People who contributed in the meantime, will be listed as authors/editors on the website. We can fight about the order, but it's not that important, I'd say. Our initial team, including @xrotwang, me and @cysouw, would stay in the initial author board regardless of contributions within a year, as the major infrastructure for setting the stuff up was made for Version 1.0.

Another possibility would be:

* to list contributors as "with contributions by XXX" in the quotation, as we now do with people who sporadically contributed code but not regularly. 

Yet another possibility would be:

* each cycle has it's authors, and all people who contributed in the past will be mentioned as contributors, if they did not contribute within the cycle of the publication. This would encourage people to keep contributing, but it would also make sure people who contributed are mentioned.

I'm open to suggestions.

**Comment by xrotwang** [comment]
I think listing everyone who ever contributed as "with contributions by" makes sense, and would be my expectation for software, for example. I think even if that list grows above - say - 20, that's still fine (and only maybe a problem regarding visualization).

**Comment by LinguList** [comment]
Allright, so all contributors, and we'll add a new category "linked
concept list". In addition, I'd say that people who have linked ten
lists or 1000 concept labels will make it to the author's board. This
may further encourage contributions. We can change this policy if we
have more lists in the future, but for the moment, 10 lists are more
than 5 %, so this is substantial enough and deserves to be acknowledged.

**Comment by LinguList** [comment]
Given that it's decided, I'm closing this issue, but we should not forget to add it the "with contributions by" to the "howtoquote" when updating the web-site.

**Comment by xrotwang** [comment]
Maybe we should move this to an issue in clld/concepticon then, to remember this.

**Comment by LinguList** [comment]
yes, followed up as [issue #23](https://github.com/clld/concepticon/issues/23) in concepticon.
