### ISSUE TITLE
concepticon-data/helpers/maplist.py assumes it knows the relative path to concepticon.tsv

### ISSUE THREAD

**Issue by Anaphory** [clld/concepticon-data#200]
concepticon-data/helpers/maplist.py contains relative paths `../concepticondata/concepticon.tsv`. If the module is meant partially as command line tool, these paths should be relative to the script file (`__file__`), not to the current working directory.

**Comment by LinguList** [comment]
This is close to #189, where the idea was to include the helper-stuff, or at least most parts of it, into the bigger api. This is not the case at the moment, but if so, we'll make sure the path is not relative (currently, helpers were only used by myself, but now, that more people start testing them, we should include them in the api as official ways to map a list quickly). Given that this is covered by #189, I'll close this issue for the moment, but we won't forget the point about the relative paths. Thanks!
