### ISSUE TITLE
Foreign list id: "???" vs. "0"

### ISSUE THREAD

**Issue by Anaphory** [clld/concepticon-data#201]
Running maplist.py on a concept list, some concepts get "0: ???" as their closest match, while others get "???: ???" instead. The former is a valid Concepticon ID, pointing to the “Set of all concepts not yet mapped to a meaningful concept set”. The latter is not a valid Concepticon ID.
Is this as intended, or is there a replacement missing somewhere in the code?

**Comment by LinguList** [comment]
It should all be ???, I'd say, as it means that it is class 8 in the scala: no match found. There is some part in the code which gives the ??? in addition to valid matches, but I didn't figure out which thing I messed up there. If you find it in lingpy and can propose a correction, I'll be really grateful.

**Comment by LinguList** [comment]
maplist is now integrated into concepticon and behaves differently. closing this issue now.
