### ISSUE TITLE
Add refinements for river terms STREAM, CREEK, RIVULET

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#203]
Here are definitions. Might be overlap, should be checked.

STREAM
a small, narrow river.
"a perfect trout stream"

CREEK (American, Australian)
a stream or minor tributary of a river.
"he drove into Adam's Creek"

RIVULET
a small stream of water or another liquid.
"sweat ran in rivulets down his back"

**Comment by LinguList** [comment]
Okay:

* STREAM  is STREAM [947]
* RIVER is RIVER [666]
* CREEK is not CREEK but CREEK (TIDAL) = small bay ("Priel" in German)

So far, no real disambiguation for the CREEK (small streem) meaning needed, as this should be covered by "STREAM", and the usage in AE is too fuzzy to make it a concept of any kind. 

"RIVULET" will not be added in the sense defined above, as this is not the name of a body of water, as a "Bach", but a transferred sense. So unless this sense is sufficiently defined, as, say "stream of liquid", it does not need to be handled by concepticon. At least not for now, unless we find a concept list that actually defines this concept.

**Comment by xrotwang** [comment]
Agree. An actual concept list **and** actual lexical data collected using this list should be the motivation for adding concept sets.

**Comment by LinguList** [comment]
Just invited Nathan to the discussion, as he brought this up. I propose to rephrase "CREEK" as "CREEK (TIDAL)", as this has obviously two senses in English.

**Comment by Schweikhard** [comment]
I think this is done.
https://concepticon.clld.org/parameters/990
