### ISSUE TITLE
Wrong linking of "pluck" to "pick up" in Satterthwaite-Phillips-423 list

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#204]
the Chinese form indicates clearly that this is "to pluck" (like "to pluck a flower").

**Comment by LinguList** [comment]
@xrotwang and @SimonGreenhill, quick question in the context of lexibank: if we find these issues of wrong linking, I usually just correct them, and a new release of Concepticon-1.1, etc. would give a different linking. Is this also covered in this form in lexibank, when we have new releases (update on concepticon -> update on some lexibank-datasets)? Or do we need to undertake specific actions, like copying the original concepticon-conceptlist to lexibank, etc.?

**Comment by xrotwang** [comment]
I think if done properly, a release of concepticon would have to be checked out when working on lexibank-data, and its release tag put into a dataset's metadata (alternatively a commit hash). I guess this could be done automatically. Will think about this a bit more.
