### ISSUE TITLE
Should we transfer lingpy's gloss-module to the pyconcepticon-api?

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#210]
We use the function lingpy.meaning.glosses.parse_gloss and the function lingpy.meaning.glosses.compare_conceptlists exclusively in the concepticon. The question is, since these are basically standalones in lingpy, whether it would not better to directly include them in pyconcepticon? In this way, we could use maplist.py as a cli-command without loading lingpy, and lingpy could later provide a wrapper for pyconcepticon. In terms of responsibilities, this would make much more sense: lingpy is used for sequence comparison, pyconcepticon is used for concept comparison.

**Comment by xrotwang** [comment]
Yes! Will have a look at the functionality and port it into pyconcepticon.

**Comment by LinguList** [comment]
In this way, we can further increase lingpy-coverage without doing
anything ;-)

**Comment by LinguList** [comment]
> In this way, we can further increase lingpy-coverage without doing anything ;-)

On LingPy, of course. 

Having the maplist.py function refactored would anyway be a good idea, as it is not necessarily user-friendly. The basic principle of input and output is still useful, I think:

**input**
```text
1 hand/arm
2 foot/leg
```
**output**
```text
1 hand/arm HAND 5
1 hand/arm ARM 5

2 foot/leg FOOT 5
3 foot/leg FOOT 5
```
So concepts are separated by empty, multiple possibilities are listed in blocks, and evaluation scores are given as an additional column (5 meaning something like, e.g., "multiple matches".
