### ISSUE TITLE
Mann -- 2004

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#22]
The wordlist for mainland south-east-asia by mann (2004) is described here, and contains some 400 items:

http://www.sil.org/resources/publications/entry/60549

The author also provides a comparison with other lists, mainly those by matisoff etc.

**Comment by LinguList** [comment]
The list has now been fully digitized and could be mapped (but it contains some awful things, especially more kinship terms, which start to annoy me).

**Comment by xrotwang** [comment]
It amazes me how much work has gone into assembling concept lists in the last couple of years without trying to link them systematically, i.e. in a machine readable way ...

**Comment by LinguList** [comment]
And we're only on the top of the iceberg here: There are in fact many more lists out, even earlier than Swadesh, and used for large collections of vocabularies, yet they are so large sometimes (1000 and more items) that I even do not dare starting to think at linking them. I am thinking more and more that we might need to adjust the workflow: maybe allowing for parts of the wordlists to be linked only automatically, as well as adding -- in these cases -- new concept sets in some "not yet approved" stage. Or we need to find collaborators or student assistent to be trained for linking the concepts. We're at 80 lists now. But there would easily be 20 more of interest, and probably some 100 more which have not yet been digitized...
