### ISSUE TITLE
Move source docs to CDSTAR?

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#223]
For all other clld apps I moved to a consolidated strategy of storing all binary content in GWDG's [CDSTAR](https://info.gwdg.de/docs/doku.php?id=en:services:storage_services:gwdg_cdstar:start) service and only keeping a catalog of pointers within repository (or database). While this would take some code to upload new docs (and keeping the catalog in sync), it would also make the repository a lot smaller, which would be helpful if we rely on clones of concepticon-data in many other projects (e.g. lexibank).

**Comment by LinguList** [comment]
If this is straightforward to do, I'm definitely supportive, but I have to admit that I don't really understand this CDSTAR from what I just read on the website. But I'm interested to learn more about it.

**Comment by xrotwang** [comment]
It's basically a filesystem with an HTTP API. For all the clld apps I want to keep the database size small, to make deployments quick and simple; so for cases like Tsammalex or APiCS, where there are multi-media files involved, I had to find a way to keep the binary content out of the database, without having to develop a second workflow for backing up files. CDSTAR fits this bill.

**Comment by LinguList** [comment]
Sounds good, especially given the large content of PDF resources we have, which are good to be in the repo, but not good to be shipped around in all applications.

**Comment by xrotwang** [comment]
Oh, I would actually remove them from the repository as well. Would you find this too problematic? They could be replace with a markdown page listing them and linking to the actual PDFs.

**Comment by xrotwang** [comment]
This mechanism may only be - slightly - impractical, if these PDFs would change frequently. But I guess that is not the case, right?

**Comment by LinguList** [comment]
removing from the repo is fine with me, I just need to know how to add new pdfs in the future (to the thing that stores them).

**Comment by xrotwang** [comment]
This would just be a `concepticon` subcommand - i.e. you move the files into `sources` and run the command. We would add `sources` to `.gitignore` so that you may still have then lying around locally, but they wouldn't go into the repository any more.

**Comment by LinguList** [comment]
Sounds very good!

**Comment by xrotwang** [comment]
The way I implemented this functionality now is as follows: We'd still use the sources directory to upload new documents - first to GitHub, later (by me) to CDSTAR. In the second step, I'd remove the files again from GitHub. This means a repository **clone** doesn't really get smaller, because all the files are still in the history. But a repository **release** will be a lot smaller. And I think, e.g. for lexibank, the recommended way to use concepticon would be fetching a certain release tarball of the data, and letting pyconcepticon work on this.

**Comment by LinguList** [comment]
I see. And for lexibank, and potentially some other projects, like, e.g., CLICS, which will work with the metadata, this will then likewise be useful. BTW: I have anyway stopped to look to diligently for ways to creatively copy only concept lists from PDFs during the last time, as it is quite tedious and makes most sense in those cases where one wants to quickly type off data. So I'd say also for the future: providing a PDF is nice, but more important, especially if the PDF is readily available online (or, say, on JSTOR), is the concept list which is typed off.
