### ISSUE TITLE
731	DRINK (FLUID) should be called BEVERAGE

### ISSUE THREAD

**Issue by nh36** [clld/concepticon-data#226]
When I was offered DRINK and DRINK (LIQUID) as two options I was quite confused. What does something drink other than a liquid. Parentheses are sometimes used for the objects of transitive verbs, I would suggest somehow making clear when this is not the case. I think DRINK (A BEVERAGE) would be less confusing, although still possibly confusing. Something like DRINK (I.E. A BEVERAGE) would be ever better. But, frankly why not just call it BEVERAGE and then avoid the ambiguity altogether.

**Comment by LinguList** [comment]
It's inherited from WOLD, and I guess you are right, calling it BEVERAGE just avoids this. Will change it accordingly!
