### ISSUE TITLE
MEAGRE OR LEAN versus THIN (SLIM)

### ISSUE THREAD

**Issue by nh36** [clld/concepticon-data#227]
I am not sure this is a real 'issue', but a few thoughts. The definition given at THIN (SLIM) is ' carrying little fat'  which makes me think immediately of 'lean'  as in 'lean beef'. If THIN (SLIM) refers only to living people, which I think it does, then this should be made clear. 

In the course of checking whether lean (of a piece of meat) was in the concepticon (it is not, nor should it apparently be), I cam to the MEAGRE OR LEAN entry. As an English native speaker there is much wrong here, MEAGRE would not normally be used of people at all, and if it is then it would mean small in stature and thin, whereas 'lean' does not have any connotation of 'sickly'. I note that MEAGRE OR LEAN only comes up in one concept list. I wonder whether THIN (SLIM) might be united with this concept. In any case, there are some thoughts.

**Comment by LinguList** [comment]
> (it is not, nor should it apparently be), 

please remember that all concepts we find in lists will be added, unless they are unspecifiable (like arrow 1 vs. arrow 2). So don't take any decisions in the concepticon as being final and not open for discussion.

Meagre or lean is some strange concept gloss, and it should be refined, as even the original gloss in the Bulakh-list contains only "lean". What they mean (and this is apparantly why I specified the concept as "meager/lean") is illustrated here:

* http://semshifts.iling-ran.ru/semantic-shifts/show.html?id=1078

So they have "lean" vs. "lean (meat)", which might justify assuming another meaning for "lean". But on the other hand, given that we only have "lean" not the other concept there, it makes not sense in keeping the "meager or lean" gloss. Thin (slim) should also only refer to people, I'd say. And lean has two potential meanings, referring to a person or to meat, as you say. And the definition, or the concept that should be expressed here is "thin in an unhealthy way", as in German "mager" when used for persons. 

I'd suppose, following your suggestion (asking for help in definitions, good glosses)

* thin (slim): only of persons
* meagre (?): thin in an unhealthy looking way (German "hager" or "mager")
* lean (?): not carrying much fat (of meat)
