### ISSUE TITLE
FISHNET mislinked in Ogden-1930-200-120 and new concept "NET" to be added

### ISSUE THREAD

**Issue by nh36** [clld/concepticon-data#228]
Is there any reason to think that Ogden-1930-200-120, who says only 'net'  refers specifically to a fishnet? (Wannemacher also gives simply 'net' in his list). There are also butterfly nets, and nets for catching other things. (By the way, I suggest saying 'finishing net' rather than 'fishnet', which to me is the name of a material that is primarily used for sexy ladies stockings.)

**Comment by LinguList** [comment]
Nope, it's an error, we should add "net" as a general tool for catching things (not for shopping), and then re-link those instances and check all fishnet instances.
