### ISSUE TITLE
Concepticon data (original stuff by Good et al.) doesn't provide links to the concepticon concepts

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#23]
I have already converted the [Good-data](https://github.com/LinguList/concepticon-data/blob/master/unlinked/Good-2010-2897.tsv) containing IDS, WOLD, and one further mapping (Usher-Whitehouse) to CSV. However, we have a problem with the URLs there, since they do create an error on the website:
- http://purl.org/linguistics/lego/concept/11

Should we still leave those urls in the file, or just discard them? The concepticon IDs, which are referenced in the data, seem to be OK, as far as I checked.

**Comment by xrotwang** [comment]
Yes, concept URLs seem to be no longer functional. One more example that keeping URLs stable isn't a technical problem, but a social one. They went the extra mile of registering [PURLs](https://purl.oclc.org/docs/index.html) for their URLs, but when the time came to redirect these, no one was there, I guess. But then, at least in theory someone could claim maintenance of the linguistics domain with purl.org and fix these PURLs, so they may be worth something.

**Comment by LinguList** [comment]
I just realized: ideally, we link the part from IDS automatically as meta-data.

**Comment by xrotwang** [comment]
@LinguList what's the status of this issue? Reading the description again, I'd say, keep the URLs - even if they do not resolve, they are still identifiers. We may replace them with a table description like
```python
...
"columns": [
...
    {"name": "LEGO_ID", "valueUrl": "http://purl.org/linguistics/lego/concept/{LEGO_ID}"}
...
]
...
```
if we want to be more terse.

I didn't understand the part about "link the part from IDS automatically as meta-data". Do you mean we just add a metadata provider `LEGO`, with the `LEGO_ID` as metadata for a concept set? If so, we'd still have to add the concept list, right? And possibly also the Usher-Whitehouse list?

**Comment by LinguList** [comment]
yes, I meant that, since we probably would not want to have this very messy thing as concept list.

**Comment by xrotwang** [comment]
Ok, so we'd add LEGO_ID as metadata for all concept sets from IDS, and that's it?

**Comment by LinguList** [comment]
Yes, I'd  say so. In some sense: LEGO is not much different from IDS.
