### ISSUE TITLE
WALL

### ISSUE THREAD

**Issue by nh36** [clld/concepticon-data#230]
Looking only at the English I see that some sources give 'wall'  and others 'wall of house' (and the like). I presume that such authors are trying to specify Wanne as opposed to Mauer. My own inclination would be to keep track of this, but if no source gives both, then perhaps there is no need.

**Comment by LinguList** [comment]
well, I agree, as we can think of a source which might do this, and a language in which both words are important, etc. And from my native speaker intuition, I prefer to have Wand and Mauer being kept distinct. Thanks for notifying.
