### ISSUE TITLE
Refine glosses for FAECES.

### ISSUE THREAD

**Issue by nh36** [clld/concepticon-data#231]
Maybe I am just not finding it, but I don't see in the concepticon a concept for the substance (feces, excrement, manure, etc.) separate form the verb (defecate, etc.). This seems like an important distinction and one that is indeed made in some of the entries that map to SHIT.

**Comment by LinguList** [comment]
FAECES: http://concepticon.clld.org/parameters/675

vs.

SHIT: http://concepticon.clld.org/parameters

But it might be a good idea to re-specify the gloss, using "excrement" or the like. Ideally, our glosses would have at least the most common alternative expressions in brackets behind them, or we would define aliases for them. But it's difficult to find a principled way for this.

**Comment by LinguList** [comment]
BTW, if you are not finding a given gloss, you may look directly [here](http://concepticon.clld.org/values), as there you have all variants in all lists, rather than by searching the concept-set-glosses.

**Comment by nh36** [comment]
In that case, it might make sense for the definition of 'shit' to spell the
word 'faeces' rather than 'feces'.

--
Dr Nathan W. Hill
Reader in Tibetan and Historical Linguistics
Department of China & Inner Asia and Department of Linguistics
SOAS, University of London
Thornhaugh Street, Russell Square, London WC1H 0XG, UK
Tel: +44 (0)20 7898 4512

--
Profile -- http://www.soas.ac.uk/staff/staff46254.php
Tibetan Studies at SOAS -- http://www.soas.ac.uk/cia/tibetanstudies/
--

**Comment by LinguList** [comment]
yes, just saw it myself. I didn't even know there are different
readings. And I tend to switch to "excrement", dropping feces in all
cases (definition and gloss).
