### ISSUE TITLE
Buck-1949-1108-847 SURPISED

### ISSUE THREAD

**Issue by nh36** [clld/concepticon-data#233]
Buck-1949-1108-847 is a gloss that is clearly transitive, but it is linked to an intransitive / adjectival meaning. I think 'surprise (someone)' should probably be split from 'surprised'.

**Comment by LinguList** [comment]
just figured that this gloss is actually not linked at all. We could link it, or leave it for the time being. But this would be another thread: add "surprise (sb)" as a concepticon gloss.
