### ISSUE TITLE
"less than"/"greater than" relations

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#254]
To characterize and use concept sets for numerals more effectively, it would be good to tag them - maybe even with a "type" annotation? And add "less than"/"greater than" relations.

**Comment by LinguList** [comment]
Sounds good, as this is feasible, and we may also need to think about getting a bit more precise in relations and the like in the future. It may also be interesting when having numeral datasets, such as [the one by Annemarie Verkerk](http://jole.oxfordjournals.org/content/1/2/91.figures-only) (but I did not really inspect the data yet).

**Comment by LinguList** [comment]
Only in practical terms, I do not yet understand what you mean by "tagging": an additional column in the concepticon? Or simply a set of metadata? The latter would probably be easier, yet of course also less exhaustive in case we add more numerals (yet one could test this if we change their type, and we could also add the integer values).

**Comment by xrotwang** [comment]
Ah you are right. I forgot about the conceptset metadata. I think that's the perfect place for this. The `-metadata.json` description would then declare the column type, and from the mapping to integers we'd also get the "<" relations.

**Comment by LinguList** [comment]
I guess this can be best done in one rush, e.g., by adding or reviewing one numeral dataset explicitly, but changing the type may actually also be a good idea, as the current Other is not necessarily satisfying, and it is also not to difficult to modify this.

**Comment by xrotwang** [comment]
Maybe we should only add this information as conceptset metadata, and not explicitely as relations? It seems to be rather special, e.g. in that the relations cannot even theoretically be applied to the other concept sets.

**Comment by xrotwang** [comment]
So what I'd do is just have the metadata:
```
CONCEPTICON_ID  NUMBER
1493                            1
```
with `-metadata.json`:
```python
  "tableSchema": {
    "columns": [
      {
        "name": "CONCEPTICON_ID",
        "datatype": "string"
      }, 
      {
	"name": "NUMBER",
	"datatype": "int"
      }
...
```

**Comment by LinguList** [comment]
Definitely, but in addition, I'd change the "Other" type (I think, it's "other" currently, or is it "person/thing"?) to "number", also to force us when adding new data, to label them as "number", which will make it easier to maintain consistency, as metadata may easily be forgotten (as the babelnet linking, which is far from being complete now).

**Comment by xrotwang** [comment]
I see, you mean the `ONTOLOGICAL_CATEGORY`.

**Comment by LinguList** [comment]
Yes, sorry for the confusion.
