### ISSUE TITLE
`pyconcepticon.data` must be replaced by files in `concepticondata`

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#268]
Currently, a part of the Concepticon data - the controlled vocabularies for tags, semantic fields and ontological categories - actually resides in a module in the python package. This is problematic when `pyconcepticon` is installed via pypi and pointed to a data directory of a different version:
```python
  File "lib/python2.7/site-packages/pyconcepticon/util.py", line 32, in to_dict
    for obj in iterobjects:
  File "lib/python2.7/site-packages/pyconcepticon/api.py", line 80, in <genexpr>
    for d in read_dicts(self.data_path('conceptlists.tsv')))
  File "<attrs generated init 9c9281d20bf37113e998192d2f44e0e44bc937b5>", line 19, in __init__
  File "lib/python2.7/site-packages/pyconcepticon/api.py", line 209, in valid_key
    value))
ValueError: invalid Conceptlist.tags: [u'body parts', u'specific']
```
To avoid this, the data from `pyconcepticon.data` should be moved to proper data file(s).

In the long run, we may still need some sort of compatibility check, where calls to the API first must make sure, the repository has a matching version.

**Comment by LinguList** [comment]
There is another issue involved in this, but we may actually solve it by automatizing the process and using a user-cache, as we do now use for lexibank:

The currently used files in pyconcepticon.data are all used for the mapping of concept lists. They essentially assemble all concept labels which could be found for a given gloss, also across different languages, and provide them in a simple form of the format "CONCEPTICON_GLOSS///actual gloss". The advantage of this is that we can even conduct international mapping, using data hosted on Russian, German, etc.. The disadvantage is that this data is currently manually prepared (that is: I wrote a script to produce the files, and I also need to update regularly, if new lists come in). If we automatize this process, using a pre-defined set of languages, or even all languages we can find, as we have them linked to glottolog anyway, we get rid of the data folder, and the only thing we need is to guarantee speed in use. And the user-cache seems to be the best option for this (it may even outperform the current approach, as we still read textfiles).

**Comment by xrotwang** [comment]
@LinguList I think we talk about different things here. I was referring to the python module `pyconcepticon.data`, i.e. the file `pyconcepticon/data.py`.

**Comment by LinguList** [comment]
yep, realized it myself. I guess, we need another issue for the data-folder in pyconcepticon, then, as this might speed up things and also make it easier to keep the mapping-data in sync with new lists being added to concepticon.
