### ISSUE TITLE
concept_map command: output all columns of source file in linked file

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#289]
Currently, only four columns are output: ID, GLOSS, CONCEPTICON_ID, and CONCEPTICON_GLOSS, but we should keep all columns in the source file to enhance mapping (e.g., if there is more than just English as language for the label).

**Comment by xrotwang** [comment]
The statistics of the mapping should also only be printed/logged to the screen.

**Comment by xrotwang** [comment]
Also the block markers for ambiguous mappings should be changed from `>>>` to `#>>>` which will lead to better viewing in libreoffice calc.
