### ISSUE TITLE
Worm vs Earthworm?

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/concepticon-data#292]
Is this a meaningful distinction?

```
1219	WORM	A generally tubular invertebrate of the annelid phylum.
2350	EARTHWORM	A tube-shaped, segmented worm found in the phylum Annelida.
```

**Comment by LinguList** [comment]
depends on the list: normally, they mean 'earthworm' with 'worm', but in German, and maybe also English, one would use the word in a broader sense: worm is the thing that looks like an ugly snake and is small, like worm in an apple (and this is no earthworm, right?). So I'd change definition and add a relation. So far we did not encounter both words in one list, but I remember a Chinese list that was forcing both concepts in the definition, so distinguishing further in the definition is useful. And your ideas as a native speaker are most welcome.

⁣

**Comment by SimonGreenhill** [comment]
I think this can be closed.
