### ISSUE TITLE
change definition of FEMALE DOG

### ISSUE THREAD

**Issue by IrenH** [clld/concepticon-data#293]
FEMALE DOG [2481] "A male dog."
... needs to be changed to "A female dog."

**Comment by LinguList** [comment]
thanks. Are you by any chance familiar with github pull requests? If so, you could just edit the file [concepticon.tsv](https://github.com/clld/concepticon-data/blob/master/concepticondata/concepticon.tsv) and submit your modifications for the definitions. If not, no worries, we'll take care of it, but maybe tell us your official name, so we can thank you in the [acknowledgments](https://github.com/clld/concepticon-data/blob/master/CONTRIBUTORS.md#people).
