### ISSUE TITLE
dixon's list has wrong numbers

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#3]
In the original Dixon list, the number 14 is missing in the source itself (apparently an entry for ear (1) which is simply not there). Furthermore, our current entry "12" is entry 11a in Dixon's list. This should be quickly updated after ID's have been changed.

**Comment by xrotwang** [comment]
Has this been addressed? Can't tell from https://github.com/clld/concepticon-data/blob/master/concepticondata/conceptlists/Dixon-1919-175.tsv

**Comment by LinguList** [comment]
Yes, I re-checked all entries and corrected them (also on the notification, it now has officially 175 entries, although the authors only show 173 in the source). Forgot to close that one!
