### ISSUE TITLE
TRUNKS

### ISSUE THREAD

**Issue by IrenH** [clld/concepticon-data#302]
are these two concept sets supposed to be the same?
TRUNK OF TREE    [776]
TREE TRUNK [344]
or is TRUNK OF TREE really TRUNK OF HUMAN BODY (the definition reads like this, but then it belongs to "agriculture and vegetation") this is rather confusing.

**Comment by LinguList** [comment]
They are a relic of erroneously assigned superfluous concept sets, and we handle them automatically, no matter what you choose, when linking concept lists. In general, we take the one with the smaller ID, so I recommend taking the 344.
