### ISSUE TITLE
Conceptlist from Grollemund et al. 2015

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#31]
In [Bantu expansion shows that habitat alters the route and pace of human dispersals](http://www.pnas.org/content/early/2015/09/09/1503793112.abstract) Grollemund et al. use wordlists for ~420 Bantu Languages containing words for 100 concepts, sampled from 159 concepts in 

> Hombert J-M, Van der Veen L, Medjo Mve P (2011) ALGAB, Atlas Linguistique du GABon (Laboratoire Dynamique du Langage, Lyon). 
> Available at http://www.ddl.ish-lyon.cnrs.fr/equipes/index.asp?Langue=FR&Equipe=8&Page=Action&ActionNum=48
> Accessed November 10, 2014.

**Comment by LinguList** [comment]
Is already mapped, will be pushed with my next PR, or should I PR right now?

**Comment by xrotwang** [comment]
Would be nice to have right now, since I'm working with the data.
