### ISSUE TITLE
[fyi] Problem of tests with growing inter-concept connections

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#329]
I ran into a test error for PR #325, as it introduced a relation for tree or wood, I suppose, or another relation I set up, which reduces the union between Swadesh and Matisoff to 300 instead of 301 concept sets. I think this is justified to some extend by now, but we should be careful with the union and intersection algorithms, when concept relations are growing. For me personally, the ultimate test case is that Swadesh-1952-200 INTERSECTION Swadesh-1955-100 yields 207, as this is the standard interpretation. If this is broken, we should review the concept relations.

If you agree with this procedure, please just close this issue, and we take it as a guide-line in case of future problems with tests.

**Comment by xrotwang** [comment]
So do we have an explicit test requiring this standard intersection of 207 concepts between the two Swadesh lists? And if we have one, it should probably be rather in `tests/test_data.py` than anywhere else.

**Comment by LinguList** [comment]
Yes, we have this test in [here](https://github.com/clld/concepticon-data/blob/master/pyconcepticon/tests/test_commands.py#L55), and sorry, it's "union" not "intersection" (intersection is 93 and SHOULD be 93).

**Comment by LinguList** [comment]
It is in fact easier to do the test now in test_commands, as there we can just invoke command line, but it should also be straightforward to introduce it there. So should we leave this issue open until that is done?

**Comment by xrotwang** [comment]
Yes, leave open.
