### ISSUE TITLE
make cli-command to re-adjust the mapping background-data

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#331]
currently, the data is stored in pyconcepticon/data, as `map-{0}.tsv`, with `{0}` being replaced by language-two-letter code (`map-en.tsv`, `map-de.tsv`, etc). The data is produced using a highly idiosyncratic script. This should be added to the `cli.py` (of course in enhanced form) and then one should be able to update the data for a particular language (or even for all languages), by typing some concepticon-command in the command line.

**Comment by xrotwang** [comment]
@LinguList where's this script? I can have a go at turning it into a proper command.

**Comment by LinguList** [comment]
would be super. I just linked North-Euralex (100%).

will submit tomorrow.
[create-data.py.zip](https://github.com/clld/concepticon-data/files/1105789/create-data.py.zip)

I'm in a rush now, so I just upload the script here. It should work out of the box. Otherwise I'll be back on my computer in about 2 hours.
