### ISSUE TITLE
action/process: think of new terminology?

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#334]
people are not content with the "ontological categories". I don't really care personally, as I see them as pragmatic terms, but we should think of making it clearer on the website, or asking people for ideas to change this name (e.g., @haspelmath proposed "event").

**Comment by xrotwang** [comment]
Hm. From the overall feedback on the published website, I wouldn't say "people are content". The main point for me is making a distinction to part-of-speech. Maybe "category" alone would be good enough?

**Comment by haspelmath** [comment]
This was one specific person (involved in Dictionaria, and generally known to be grumpy about Concepticon), so I wouldn't worry too much. "Action/process" is fine, I think, and while "event" would be shorter, I see no good way of abbreviating "person/thing", so one needs "X/Y" labels anyway. I'd recommend leaving things as they are.
