### ISSUE TITLE
Rename ConradandDye1975-102 to be more inline with other lists

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#352]
To enforce consistency in naming concept lists, *ConradandDye1975-102* should be renamed to *ConradDye-1975-102*

**Comment by xrotwang** [comment]
@LinguList are you ok with this change? If so, I'd roll it into the work on #100

**Comment by LinguList** [comment]
Yes, definitely!

**Comment by SimonGreenhill** [comment]
(Sorry, my bad)
