### ISSUE TITLE
Duplicate concept set gloss *OSMANTHUS FRAGRANS*

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#354]
Guess there should be check preventing this from happening.

**Comment by LinguList** [comment]
ups, and it even occurs in no list in the end. I know why I inserted it, and when this happened: when working on BeijingDaxue-1964-905, they have all these tree names plus tree flowers, and adding tree flowers, I added relations, so sweet olive is one name of the tree, the other is osmanthus fragrans, and olive flower is one other name of the flower. I must've forgotten that I already included it before when working on this. We should definitely have a check, maybe even some fuzzy matching test that would give us the most similar concept sets as is for now, so we could review them (although this could stay a plugin that would not need to run all the time).

**Comment by xrotwang** [comment]
Ok, so the solution is to drop both instances from `concepticon.tsv`?

**Comment by LinguList** [comment]
sorry, no, keep one, since we have it in the relations, and I figured, having "plum flower" vs. "plum tree", it would confuse further mapping if we have "olive flower" without the corresponding tree. But I'd probably re-think how to name it, as this blabla-fragrans is far too technical. 

I'll try to come up with some solution and will then mark the concept with the higher ID as duplicate.

**Comment by LinguList** [comment]
I just pushed my proposal (changing OSMANTHUS FRAGRANS to "olive flower" and retiring the latter one), but the general test would still be useful. I also realized, when I checked the tree vs. tree-leave concept relations, that I annotated those as "haspart", which of course makes sense, but I think we did not really discuss it, also to which degree we would allow for additional relations beyond "broader narrower".

**Comment by xrotwang** [comment]
Adding a test turned up a couple more:
```
ERROR:2747: duplicate conceptset gloss: OSMANTHUS FRAGRANS
ERROR:2752: duplicate conceptset gloss: INSTEAD
ERROR:2780: duplicate conceptset gloss: YEAR BEFORE LAST YEAR
ERROR:2781: duplicate conceptset gloss: YEAR AFTER NEXT YEAR
ERROR:2786: duplicate conceptset gloss: CLOG (SOMETHING)
ERROR:2913: duplicate conceptset gloss: IMMEDIATELY
```

**Comment by xrotwang** [comment]
I guess, Concepticon is getting big :) Probably there is an upper limit on concept sets which we can deal with consistently - somewhere between 3,000 and 5,000, I presume.

**Comment by LinguList** [comment]
Yes! Useful to think of how to check the 3000 already now. E.g consistent definitions, etc., But for this, we'd need more personell.

**Comment by xrotwang** [comment]
Ok, linked to the other duplicate concept sets are the following lists:
```
ERROR:Dellert-2017-1016:585: invalid value for concepticon_id: 2913
ERROR:BeijingDaxue-1964-905:26: invalid value for concepticon_id: 2781
ERROR:BeijingDaxue-1964-905:28: invalid value for concepticon_id: 2780
ERROR:BeijingDaxue-1964-905:547: invalid value for concepticon_id: 2786
ERROR:BeijingDaxue-1964-905:900: invalid value for concepticon_id: 2752
```

**Comment by xrotwang** [comment]
So I'd say we solve the OSMANTHUS FRAGRANS case as proposed by you and delete the other duplicates.

**Comment by xrotwang** [comment]
Which will leave us with holes in the series of concepticon set IDs, but I think that's ok; we could have a small command that gives us the smallest un-used integer as potential new concept set ID.
