### ISSUE TITLE
Use numeral bank to define all numbers?

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/concepticon-data#368]
https://github.com/glottobank/lexibank-data/blob/master/datasets/numerals/concepts.csv

**Comment by LinguList** [comment]
Don't we have this covered via the numeral metadata? It's a list of integers @xrotwang created...

**Comment by SimonGreenhill** [comment]
Ahh, ok. I just noticed there was a lot missing in the lexibank concept list.
