### ISSUE TITLE
cross-linguistic account on age of acquisition

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#381]
* https://www.ncbi.nlm.nih.gov/pubmed/26276517

In some sense, they must have made their own concepticon... Unfortunately, they share their data only in PDF...

**Comment by LinguList** [comment]
They just provided me with their data, excellent, and they seem to have a follow-up article on this!

What's left to do is now:

- [ ] link to concepticon (ideally ALL terms, even if it's something like "airplane", as concepticon could help to integrate data for psycholinguistics/psychology as well)
- [ ] add bibliography
- [ ] add short note about the paper
- [ ] don't forget to thank Magdalena Łuniewska in our acknowledgments

**Comment by chrzyki** [comment]
Current progress [here](https://github.com/chrzyki/concepticon-data/blob/luniewska/concepticondata/conceptlists/Luniewska-2015-299.tsv) and [here](https://github.com/chrzyki/concepticon-data/blob/luniewska/concepticondata/conceptlists/Luniewska-2015-299.tsv-metadata.json) (metadata).
