### ISSUE TITLE
New Concepts (non-essential - for future reference)

### ISSUE THREAD

**Issue by IndianaTones** [clld/concepticon-data#383]
lighter
hibiscus
sheath
kola nut
manure
rinse
couscous
sprinkle
toothpick
porridge
put on
shawl
ceramic pot
handful
baptism
fonio
shea-butter
dip
Baobab leaf sauce
sift
macari
whirlwind
stroll, wander
cemetery
greet
fodder
Fula person
shroud
cowry
granary
weaver
question see ASK (INQUIRE)
sesame
gravel
shard
totem, shrine
spice
co-wife
heal
blow nose
unravel
Dogon person
attach
bump
burnt
you pl
insult
pod
unroll
shell
tight
point (verb)
date palm
lower, bargain
apiary
agree
filter
I
wrestle
coop (chicken)
travel
shed
mint
henna
marabout
LIE (cause)
snuff
spend or pass the night
hot season
dried meat (or fruits)
crazy (noun)
Ramadan
it is not
crumple
deplete, use up
plaster (verb)
roll up
bachelor, unmarried (male)
leatherworker (caste)
Ramadan
too, also
rash
alms, donation
Imam
sack
put hat on
transform
Muslim (person)
Fajr
discuss
Maghrib
file (verb)
hatch (verb)
jab
STRETCH (body)
tight, cramped, close
turn on
stack
scarification
sprinkle
trigger (noun)
Isha
I
Asr
surname
peck
Guinea worm
dipper
shorten
luggage, baggage, bags
joking cousin
collect firewood, scavenge
bundle
since
offer condolences
trust, entrust
singer
tenth
ululate
pour back and forth
crooked, bent
namesake
Bozo person
taboo
fifth
until
ruined
thus, therefore
infant
whatchamacallit, so-and-so
dizzy
share
snatch
break fast
nail (verb)
trust, confide
pick, remove
poor (person)
allow, authorize
plump
tilt
Mossi person
saw
possession, belonging
Griot caste
take away
newlywed
if
rich (person)
termite mound, termitary
cement
brew (verb)
explode
ceramic pot
left-handed person, lefty
pluck
sip
coughdrop
shard
hoe
sixth
collective hunt
unable
Arab person
clap, applaud
guava
loan
salutation, greeting
vaccinate
carrion
stirrup
aim
crumble
plead, beg
lean
better
pilgrimage
lean (verb)
tie a knot
saltlick
worn out, rag
nibble
incise, slice
description
outhouse
file (verb)
holiday
headache
Bamana person
foreigner, European
cushion
dyer caste
lightening
tangle
flint
slurp
prepare
wax
sulfur
shed, shelter
ink
tickle
sponge
deaf-dumb person
faint
congratulate
gush
poke
meeting
pedal
cave    in
judge (verb)
patience
inheritance
trust (verb)
collective hunt
exit
plug
stack
crumple
sustain
wilderness
water v.
scoop
CUT noun
WASH clothing
transplant
noun
times
receive
take down
entrance
neighborhood
LAZY (noun)
slice
beg
tracks
staff
put down
disperse
smell (noun)
unfold
butt (verb)
tighten
leak
unlock
chase away
saddle
remove
pose
be or become married
leprosy
stroll
mustache
remainder
take down
hide
fine
accustomed, used to
tangle
stroll
track (verb)
nose ring
spring (verb)
snap
spill
scrub
trick (noun), ruse
cast (verb)
make a rope by weaving
grindstone
take out
draw a line
imprison
stride, step (noun)
travel
leftovers
graft
also sap
profit
collapse
later
hammer (verb)

**Comment by LinguList** [comment]
Okay, we'll also need definitions for those, plus some additional information, I'll run you through this later.

**Comment by LinguList** [comment]
Hey, don't be angry with me @IndianaTones, but I will close this now, as I suppose that it should come out of the data, and now that we have the procedure to allow for not yet linked new concept sets by preceding them with the !, we can later, when we finalize the list for dogon/bangime, etc. submit a new list of proposed concepts and enhance concepticon.
