### ISSUE TITLE
pyconcepticon API tutorial (README.md) doesn't work for Python 3.x

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#384]
Ordered dicts are iterable view objects but not lists in Python 3.x. Thus, the `pyconcepticon` API code snippet fails:
```Python
>>> conceptlist = api.conceptlists.values()[0]
>>> conceptlist.author
```
For Python 3.x something like this, though somewhat more unwieldy, works:
```Python
>>> concept_list = list(api.conceptlists.values())
>>> print(concept_list[0].author)
```

**Comment by LinguList** [comment]
True, I think I was actually always doing that, as I only use py3, disregarding the API. As the key tasks is usually anyway to get a concrete concept list, I think we can just modify the API description without modifying the code.

**Comment by chrzyki** [comment]
Yes, I agree, a change of the API description/documentation would be absolutely sufficient. It is just something I noted that might be a stumbling block for new users.

**Comment by IndianaTones** [comment]
Speaking of new users (using Python version 2.7.0) both,

>>> conceptlist = api.conceptlists.values()[0]
or 
>>> concept_list = list(api.conceptlists.values())

produce the same error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/clldutils-1.13.10-py2.7.egg/clldutils/misc.py", line 197, in __get__
    inst._cache[self.__name__] = self.fget(inst)
  File "/Users/ah104/Library/Python/2.7/lib/python/site-packages/pyconcepticon/api.py", line 94, in conceptlists
    for d in read_dicts(self.data_path('conceptlists.tsv')))
  File "/Users/ah104/Library/Python/2.7/lib/python/site-packages/pyconcepticon/util.py", line 32, in to_dict
    for obj in iterobjects:
  File "/Users/ah104/Library/Python/2.7/lib/python/site-packages/pyconcepticon/api.py", line 94, in <genexpr>
    for d in read_dicts(self.data_path('conceptlists.tsv')))
TypeError: __init__() takes exactly 16 arguments (15 given)

**Comment by xrotwang** [comment]
which version of pyconcepticon is this? Installed from pypi or from a repository clone?

**Comment by IndianaTones** [comment]
Installed from pypi

**Comment by LinguList** [comment]
okay, installing from repository using git clone https://github.com/clld/concepticon-data is probably needed, as this will guarantee you use the latest version...

**Comment by xrotwang** [comment]
Yeah, at some point we changed the data model in a non-backwards compatible way. This should be fixed with a new pyconcepticon release, but realistically, we'll do this together with a new concepticon-data release.

**Comment by LinguList** [comment]
Yes, so @IndianaTones, sorry for troubling you, but please try the github-clone approach mentioned above. If there are problems, ask me tomorrow, or @chrzyki (who has also a mac) for troubleshooting.

**Comment by chrzyki** [comment]
Fixed this by using concepticon-data from GitHub & going to update the README with a small note for Python 3.x.
