### ISSUE TITLE
Enhance basic statistics for Wordlists during mapping process

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#390]
I just discussed with @chrzyki how to add new functionalities into the CLI. The basic idea is:

1. a command ```concepticon mergers conceptlist``` which spits out the concepts which are merged.
2. a command ```concepticon check conceptlist``` which tests for general conformity and will spit out problems, like non-unqiue IDs etc. Current functionality is lacking, as it only gives us the first non-unique key, which is tedious if you have 100 non-unique ones, etc.
3. the possibility to have user-defined potentially new concept sets for the time while working on a project. We currently define them by leaving the concepticon_id empty and adding a "!" in front of the concepticon gloss. All this applies to local concept-lists, not to our data in Concepticon. But a command ```Concepticon newconcepts conceptlist``` or similar would ideally provide new lines with free concepticon IDs where users can fill in the missing definitions etc. I used my custom workarounds when working on larger datasets mysefl, but I think we should, with more people working on this, try to make it more comfortable for our users.

@chrzyki will first start looking into this. I added some hints with ```@todo``` marks to the testing-branch, and I hope we can have have a first PR with some of these new ideas by the end of the week.

**Comment by chrzyki** [comment]
I'd like to move the Dogon scripts that, partially, tackle these tasks into the code base. To what extent does it make sense to have `check` (which would be new) and `test` (which already exists) as distinct arguments? From a programmer's point of view I can see the difference, from the end-user's perspective this might be confusing. Oh, this also raises the issue that the stack traces `test` throws aren't particularly user-friendly. Maybe we could add all these functionalities under the `test` umbrella and generate a dedicated (human/end-user readable) report of issues with new concept lists?

**Comment by LinguList** [comment]
Check is for those people who currently work on a given concept list and want to test this particular concept list and this list alone. Test is to trigger all tests which will re-test all data according to our criteria (a short cut to avoid some problems with Nose).

**Comment by chrzyki** [comment]
Alright, makes sense. So we should/could disambiguate this by means of parameter explanations/help files/documentation/etc.?

**Comment by xrotwang** [comment]
Moved https://github.com/concepticon/pyconcepticon/issues/2
