### ISSUE TITLE
Concept linking problem for WAKE UP

### ISSUE THREAD

**Issue by tresoldi** [clld/concepticon-data#393]
As discussed in pull request #392 , we might need to check the transitivity of the verbs, discussing cases (especially already mapped ones) such as WAKE UP/WAKE SOMEBODY UP, BURN/BURN SOMETHING, BATHE (ONESELF)/BATHE SOMEONE ELSE, etc.

**Comment by Schweikhard** [comment]
The transitivity pairs mentioned are implemented by now. Many more are still missing but that would be a separate (new) issue.
