### ISSUE TITLE
simple html website with minimal js support to lookup concepticon concepts

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#403]
when linking, we often search concepticon concepts by re-writing or re-spelling some senses. Obviously, this could be enhanced, as the website does not list all recent glosses, and the github version is only on text. I imagine a simple html generated from our concepticon data, with minimal js that can be opened locally and lists:

1 the normal concepticon glosses
2 the "reflexes" in other lists (also linking to a gloss)
3 all in different languages

I guess this will greatly enhance working locally on adding a concept list, as one just has to open the HTML locally. Simple auto-suggest, etc. could be easily added. In the spirit, this is similar to the [clts](http://calc.digling.org/clts/) lookup for sounds.

**Comment by LinguList** [comment]
first demo is [here](http://calc.digling.org/concepticon/)

**Comment by tresoldi** [comment]
This is actually very good, I can see myself using it as it is right now. :+1:

**Comment by LinguList** [comment]
Thanks, I'll gladly share the details on the algo with you, as this is SO SIMPLE, but just uses the major principle as I mentioned before: store in memory, don't compute.

**Comment by tresoldi** [comment]
Yes, I'm looking at the `getGlossesBySimilarity` right now. As usual I plan too far ahead and build a cathedral when a hut would be faster and just as good.

**Comment by LinguList** [comment]
I ask myself, @xrotwang and @SimonGreenhill, how we should deal with this? I wrote a 
```
$ concepticon html
```
function that creates this output. The website would be stored in the concepticon package in a html folder (only three files). But we might want to add this to a gh-pages branch as well, so that it can be regularly updated, or, alternatively, we would point users that they can use the offline version, plus the link where I just put it for the future?

We might even think of including a similar lookup to the clld-version, although I think it is really rather for developers that this is needed (but the JS code is minimal, and I checked it with pycharm, so no unused variables this time).

**Comment by xrotwang** [comment]
well, this could certainly be served by http://concepticon.clld.org
And I guess starting with the next release we should switch to a more frequent release cycle anyway?

**Comment by LinguList** [comment]
Yes, given the new contributors we have now, we probably want to have more regular releases. 

I always dreamed of a web-version of ```$ concepticon map```, but I think, if we add this, it is even enough functionality for most linguists who want to add a 100 concept list and are ready to spend an hour for this (be it their own hour or the hour of their poor Hiwis).

**Comment by LinguList** [comment]
Should I just submit my current code as PR? It does not harm anything, but I don't know how to test this.

**Comment by xrotwang** [comment]
yes, PR is good

**Comment by LinguList** [comment]
the app is there now, closing this.
