### ISSUE TITLE
Check for reduction of <NA> concepts.

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#408]
maybe by automatically re-linking all NA concepts in all lists and proposing changes.

This could potentially even become a new command.

**Comment by xrotwang** [comment]
Attached is a file I created by 
- calling `Concepticon.lookup` on each label of a <NA> concept
- limiting the results to the first match with similarity score of 1 or 2.

[notlinked.txt](https://github.com/clld/concepticon-data/files/2824290/notlinked.txt)

Will include this code in `pyconcepticon`.

**Comment by LinguList** [comment]
I didn't say that they need to be completely included, but I did say they should be stored and shown somewhere, so other people can help and work on the potential errors, and submit them. At least this aspect was the one I deem important. So far, we share lists in github issues in txt format, or as excel, we don't have a workflow from raw data to mapped list, and this is not good, as it means, I have lots of data on my computer that others don't have.

**Comment by LinguList** [comment]
In fact, this is probably not hte righ tissue, to discuss, I was mainly concerned with our [unliked lists](https://github.com/clld/concepticon-data/tree/master/unlinked).

**Comment by tresoldi** [comment]
So you mean like in a development branch? That would actually be nice, but we should have checks in place to make sure we don't unintentionally release it.

**Comment by LinguList** [comment]
simpler: move unlinked lists to a new repository, I'd not want to fiddle with branches, but having a place to store unlinked lists would be usefu.

**Comment by xrotwang** [comment]
Oh yes! Now that pyconcepticon is in its own repository and can work on any concepticon-data-like repos, moving unlinked and experimental lists to a dev repos would be easy. Although, considering that the core data like concepticon.tsv would need to be merged every once in a while, a branch may be a better idea. But then, branches prove to be a quite high barrier to entry for newcomers. So, I'd opt for a `concepticon/concepticon-dev` repos.

**Comment by LinguList** [comment]
Yes, and in this repos, we can have a folder per concept lists, including potentially also the PDF, the bibtex, etc. The unlinked list and the linked list. This would avoid sharing excel files we receive at times from people inside github issues only. And if a new list comes in, we could add it there, etc.

**Comment by xrotwang** [comment]
And then a `concepticon move` command to move a finished list to the main repos?

**Comment by tresoldi** [comment]
Yes! A new repository sounds good, also considering that `concepticon-dev` itself might end up with branches, which would make everything too complex.

**Comment by xrotwang** [comment]
I wouldn't want to have a different directory layout in `concepticon-dev`, though. So no "a folder per concept list", but PDFs go into `sources`, refernces go into the BibTeX file. This way we can re-use the consistence check for `concepticon-data` as progress check for the dev repos.

**Comment by LinguList** [comment]
Yes, good idea. The only problem is where to put xlsx files and the like, which should not be on one person's computer. We may need to add another folder for that? Or place it in sources, as a spreadsheet is as well a source of a concept list?

**Comment by tresoldi** [comment]
I'd go for placing in sources.

**Comment by xrotwang** [comment]
Still, `sources` seems the best option. I'd say by the end of the dev workflow - i.e. when the list is ready to be moved to the main repos - there may only be a pointer in the list description or notes relating the list to the source sheet.

**Comment by xrotwang** [comment]
will move scaffolding and `unlinked` over to `concepticon-dev` today.

**Comment by xrotwang** [comment]
So regarding the 150 not-linked concepts above: Should I have a go and create a PR and someone else can review and merge?

**Comment by LinguList** [comment]
I'd rather have two people look at the list independently, then checking the differences, and then making the PR, and I'd review this. Some things are tricky, in this automatic merge, which need to be double-checked. @tresoldi and @chrzyki, could you quickly go through the list and exclude those cases where you are not fine (or replace them by better values)? This will be more efficient than a PR, as there, we'll have discussions on every item.

**Comment by xrotwang** [comment]
Ah, sorry. Only read the last comment now. As far as I can tell, I only addressed rather clear-cut cases, though. So I think no time has been wasted yet :)

**Comment by LinguList** [comment]
No problem, I'd say: @chrzyki  and @tresoldi start with their review, I'll be last, once they have gone through it.
