### ISSUE TITLE
Pagel-2018-XX: Rank order of stable words across language families

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#421]
* http://rstb.royalsocietypublishing.org/content/373/1740/20160517.figures-only

This is a very small list, not of high priority, but could be easily mapped:

The relevant table is Table 1.

**Comment by chrzyki** [comment]
Taking this.

**Comment by chrzyki** [comment]
Merged in #433 (this PR and the discussion is also a helpful reference for linking lists that are based off of basic lists).
