### ISSUE TITLE
Enhance Concept Mapping

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#422]
The way automatic concept mapping works can be improved, especially from an end-user perspective. @LinguList suggests a number of ways in #398. Amongst those:

- an interactive way of working with concept mapping suggestions (e.g. in the form of a small web app)
- POS information and definitions
- better (more approachable? understandable?) similarity levels
- better handling of malformed input in the `Gloss()` class

**Comment by xrotwang** [comment]
Moved https://github.com/concepticon/pyconcepticon/issues/3
