### ISSUE TITLE
Release a new version of pyconcepticon to fix clldutils.csvw issues

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#431]
Due to recent changes in the architecture of [clldutils](https://github.com/clld/clldutils) (particularly `clldutils.csvw`) the `pip`/PyPI version doesn't work with concepticon any longer. Working with a development installation from a local repository (`python setup.py develop` etc.) of course works as expected.

We should either

- release a new version of `pyconcepticon` to make the `pip install` way again compatible with recent changes

or

- only ever recommend the `python setup.py develop` way and remove `pyconcepticon` from PyPI.

The last option probably isn't desirable, but as of right now I'm not quite sure what the workflow for releasing `pyconcepticon` individually as a package was in the first place. Any input is appreciated. :)

**Comment by LinguList** [comment]
Releasing should wait until we have decided what we want to put in the release: e.g., do we want improved CLLD, etc? Even the CLLD app will need some refinement now, so while we can think along the lines of having this done by end of, say, April, it is not before then that we should draft a new release. Ideally, I'd like to have the improved search procedure included there, and a little search field, where people can use something along the example [here](http://calc.digling.org/concepticon/) to quickly search for a given concept set.

**Comment by chrzyki** [comment]
Ok, cool. Totally understandable. Should we then, for the time being, just recommend the workflow with installing the package locally in development mode?

**Comment by LinguList** [comment]
yes!

**Comment by chrzyki** [comment]
Done & thanks for the input: 56f18bfbdcd7d17f6f2ffc36daef87cb0f779583

**Comment by SimonGreenhill** [comment]
Does this also fix https://github.com/clld/concepticon-data/issues/374?

**Comment by LinguList** [comment]
It will fix it, if we go for @xrotwang's new structure by which all data is arranged as we have it in clts, with one `src/` repository. Our problem with the lists is that we don't have a `MANIFEST.in`, but with the new style, this won't be needed, and data would be available from within the repo by pip-installing.

**Comment by LinguList** [comment]
At least that's how I understood it. But there's still some work to do on concepticon. However, my current priority is CLICS. The goal is to have a first version with internet and CLLD by beginning of March.
