### ISSUE TITLE
Recreate the Links should be part of the API

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#437]
The code I currently use is the following: 

[create-data.py.txt](https://github.com/clld/concepticon-data/files/1769974/create-data.py.txt)

I use it to create the files in pyconcepticon/data, with ending according to the languages (in two-letter code).

If we integrate this in the api (as the HTML routine, which creates the standalone app in JS for matching), it will be more consistent.

**Comment by xrotwang** [comment]
As far as I remember, I already turned this into a command.

Johann-Mattis List <notifications@github.com> schrieb am Do., 1. März 2018,
07:21:

**Comment by LinguList** [comment]
Ups. Sorry, I actually thought it might have been, but I was searching yesterday and just didn't find the command ...

**Comment by LinguList** [comment]
I see: write_linking_data! Sorry!
