### ISSUE TITLE
POINTED (SHARP) as in German "spitz" is missing

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#443]
This concept recurs in quite some lists, but we have not really distinguished it so far, I'm afraid.

**Comment by LinguList** [comment]
So before releasing, this should be looked for. I'm also inviting @Schweikhard to help here. But no hurry now, we discuss this during the next week's group meeting.

**Comment by Schweikhard** [comment]
Not sure but I think all the lists here refer to pointed (sharp/spitz): https://concepticon.clld.org/parameters/372
Only exception would be Buck who refers to the noun point/Spitze.
Which other meaning should pointed have? Punctured?

**Comment by LinguList** [comment]
Maybe your right. I think I never used the word in English, so it surprised me. 

But there are missing concepts:

- https://concepticon.clld.org/values/Sun-1991-1004-806

And this one is wrong:

- https://concepticon.clld.org/values/Bulakh-2013-870-116

And for these, we could add another concept, "point (of weapon)":

- https://concepticon.clld.org/values/Bowern-2012-644-401
- https://concepticon.clld.org/values/Buck-1949-1108-670
- https://concepticon.clld.org/values/Kusunda-1972-337-309

Do you think, @Schweikhard, you can propose a solution here?

**Comment by Schweikhard** [comment]
I see - didn't look for missing concepts.
My suggestion would be to add Sun to the existing concept of pointed (and rephrase the definition maybe)
and to add a new concept that refers to the noun meaning Spitze (no matter whether of weapon or not, so not only Bowern and Kusunda but also Buck and Bulakh would be included). We could call it point (pointed end).

**Comment by LinguList** [comment]
I assign this to you, @Schweikhard. Thanks in advance!

**Comment by Schweikhard** [comment]
Okay! Btw, which repository is the one I should use now? This, or concepticon-dev?

**Comment by LinguList** [comment]
clld/concepticon-data, as this is not a new list.

**Comment by Schweikhard** [comment]
Done!

**Comment by LinguList** [comment]
NIce, but please leet me review next time, okay?

**Comment by LinguList** [comment]
Already saw it, it's okay!
