### ISSUE TITLE
Standardize lookup app

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#444]
Following the discussion at https://github.com/lingpy/clics-data/issues/19 I propose to rename 
- `html/concepticon.html` to `app/index.html`
- the command `html` to `app`

The idea is that each repository which provides an `app` command will then direct the user to open `<repos>/app/index.html` in the browser to run the app.

**Comment by xrotwang** [comment]
@LinguList ok with this?

**Comment by xrotwang** [comment]
We could then standardize this by adding a `appdir` property to [`Api`](https://github.com/clld/clldutils/blob/7388c0d3cf7ff6b6b275470ac206f5500d34cb05/src/clldutils/apilib.py#L56), and maybe even provide a command wrapper in `clldutils.apilib` - say a decorator which calls the decorated function and then runs `webbrowser.open(api.appdir)`.

**Comment by xrotwang** [comment]
I would remove the `app` directory from the repository, though, since it's something that can be automatically recreated from the data. Rather, the `app` command could have a `--recreate` flag.

**Comment by LinguList** [comment]
Sounds all very good to me, the only question I'm asking myself is: where would I put the templates if we remove the app dir? For now, we have an unfortunate (but easy for developing) mix of js-code, css, html, PLUS the data that comes in. For developing, this is easy, but less elegant for the whole idea, I am afraid.

**Comment by xrotwang** [comment]
Ok, I see. Why not keep the `app` directory in the repos, but put all created content under `app/data`. Then
- presence or absence of `app/data` can be used as flag to indicate whether the content has been created already
- `app/data` can be put in `.gitignore` to make sure we don't distribute inconsistent states of created data.
