### ISSUE TITLE
Link to cookbook/usage in CLLD App

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#448]
If we publish version 1.1 now, we need to have one quick illustration of what the API can do, as the API was so far never addressed, apart from in some tutorials. This should be ideally linked by the CLLD app, so that people know that linking their data manually is not the only way. It may be sufficient, though, to just mention the API on github and THEN adding more info here.

**Comment by xrotwang** [comment]
What about this https://github.com/clld/concepticon-data#usage ?

**Comment by xrotwang** [comment]
Moved to an issue for the clld app: https://github.com/clld/concepticon/issues/33
