### ISSUE TITLE
Tests  the Concepticon

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#45]
When working on the concepticon, more things come to mind, which we need tests for, and I suppose we summarize them here, to not forget about this.

* tests for concepticon.tsv should check for the number of categories, like person/thing, but also for the rough semantic field (animals, the body), etc., since spelling differences may create errors here, and the categories and fields are actually fixed

Of course, more tests are surely needed, but this is what I can think about at the moment.

**Comment by xrotwang** [comment]
I closed this issue, because I think it's easier in terms of organization and logistics to open new more concrete issues whenever we feel the need for a new test, rather than keeping this issue open all the time and adding new requirements as comments.

**Comment by LinguList** [comment]
I agree.
