### ISSUE TITLE
Bengtson-2017-12: very stable list

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#450]
```
@Book{Bengtson2017,
  address   = {Cambridge},
  author    = {Bengtson, John D.},
  publisher = {Mother Tongue Press},
  title     = {Basque and its closest relatives: A new paradigm},
  year      = {2017},
  timestamp = {2018.03.06},
}
```

The quote is on p 15:

> In the following experiment we have taken twelve basic word meanings from the
> Swadesh list (blood, die, ear, eye, fire, heart, horn, not, smoke, thou, tongue, tree) 2 and
> compared the semantically equivalent words from seven “mystery languages,” all spoken on
> the European continent. In the first step of this experiment we shall ignore the identity of the
> languages and simply compare the words on the basis of superficial similarity.

**Comment by SimonGreenhill** [comment]
Done in https://github.com/clld/concepticon-data/pull/454
