### ISSUE TITLE
Badges for the Concept-Lists

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#46]
In order to allow for quality control and the like, it would be great if we could create badges for all concept lists processed. This would answer questions like:

1. are there mergers inside the list, that is, are two or more concepts linked to the same concept sets?
2. [maybe silly, but might be interesting] how often do the concepts in the very list occur in other lists on average, that is, how "unique" is the list regarding its inventory
3. [also not necessary, but good for proof-checking] how large is the levenstheint distance on average between the concept labels in the list and the concept labels of the concepticon
4. which lists are most similar in terms of overlaps in concepts to the given list

I think this may be some interesting information we could assemble automatically whenever parsing the concepticon-data in, and it would be worthwhile to show the information. It may be enough to write a script that computes the values and to add them automatically to the file conceptlists.tsv, since it would probably here, where the information would be displayed afterwards...

**Comment by xrotwang** [comment]
ad 1.: So "merger-free!" would be the badge, and the bad concept lists don't get it?

ad 2.: This is something, I'd rather add to the published concepticon, e.g. as column in the [concepts table](http://concepticon.clld.org/contributions/Yakhontov-1991-35) of a concept list.

ad 4.: Again something, I'd rather have in the published concepticon.

**Comment by LinguList** [comment]
reg. 1: yes, and we also need "mapped all", because we have parts of lists which have unlinked concepts.

reg the rest: I agree, but how should we manage that? With three more columns in the conceptlists.tsv, or with an extra meta-data file, that is computed, or as a routine in the clld-app?

**Comment by xrotwang** [comment]
The clld app has a real database behind it :) so computing all these things on the fly shouldn't be much of a problem. We'd need a clear metric for 4., though, and maybe a threshold. Then we could display something like "related lists".

**Comment by xrotwang** [comment]
Where would you want to see the badges? In a `concepticondata/conceptlists/README.md` that is created from a script?

**Comment by LinguList** [comment]
Well, as a metric which is rather stupid but interesting enough, I suggest Jaccard:

* number of shared concept sets / number of the union of concept sets [or the other way round, I always forget the direction of jaccard]

This will make lists like WOLD look very different from Swadesh, because of the size, but this is here also exactly what we might want to have: showing which lists are similar both in size and in the concepts they cover.

But this metric is probably better tested in advance. I already played around with it, since I was curious whether I could find who copied from whom, so I can produce some example and give a threshold and the like.

**Comment by LinguList** [comment]
I guess ar eadme in conceptlists would be ideal.

**Comment by xrotwang** [comment]
I moved the missing parts of this issue to a new issue for the concepticon app https://github.com/clld/concepticon/issues/6
