### ISSUE TITLE
Deviating concepts for LexiRumah

### ISSUE THREAD

**Issue by Anaphory** [clld/concepticon-data#463]
The LexiRumah concept list (http://www.model-ling.eu/lexirumah/parameters) has the following concepts in it, for which Concepticon only contains only related concepts.
(There are concepts which are entirely new, but that needs less discussion and is therefore a different issue.)

We have:
 - BATHE (SOMEONE), a transitive conterpart to BATHE [oneself] (138)
 - PLANT YAM and PLANT RICE, which are more specific forms of PLANT (1486). (Visual inspection says about half of our languages appear to have non-cognate words of these concepts, and I think there is indication of semantic shift going on between those, if you need an argument for including those more detailed concepts.)
 - Because some of our languages differentiate between male and female SARONG (2413), we specifically have FEMALE SARONG in our list (and I don't know why not both).

I would argue for inclusion of BATHE (SOMEONE), PLANT YAM and PLANT RICE, but I would be willing to accept linking to SARONG and specifying in one of our notes that if the concept is ambiguous, we want the female one.

**Comment by LinguList** [comment]
Here's the typical way to proceed: 

- [ ] have your database published (well, you have a version, etc., so we can quote it)
- [ ] prepare a PR for concepticon with the new concepts, the reference (we don't need a doi, but maybe a weblink to each concept, etc.)
- [ ] add missing links to concepticon.tsv
- [ ] add short description to conceptlists.tsv
- [ ] assign @lingulist, @chrzyki, and @tresoldi as reviewers (we will divide work among us)

Be careful with fuzzy links in general, we can discuss this during your PR.

**Comment by Anaphory** [comment]
What do you mean by references for the concepts, what level of scientificness and detail do you want?
Wikipedia links? Where would I put them?

**Comment by LinguList** [comment]
I mean that I'd like to have a column URL that specifies how I can VIEW the concepts in lexirumah. We have that for ABVD as well, check out the list as Blust-2008-210. Users can then directtly go to lexirumah if they find the concepts interesting. But up to you whether you would like to have this...

**Comment by Anaphory** [comment]
Ah, excellent. I was hoping that's what you meant, that's easy.
