### ISSUE TITLE
Fail on glosses with leading or trailing spaces

### ISSUE THREAD

**Issue by tresoldi** [clld/concepticon-data#474]
@Anaphory [pointed to the fact](https://github.com/clld/concepticon-data/pull/467#issuecomment-382791407) that there is no checking of eventual leading/trailing spaces in the glosses, which should not be accepted as it is difficult to imagine a case where they'd be needed and as it makes debugging hard when such spaces are accidentally introduced.

The place for running such check (which would essentially be an `if gloss != gloss.strip()` and could be extended to other columns) is probably  `concepticon-data/pyconcepticon/check_data.py`, with a test to make sure it is raising a `ValueError` exception.

Thoughts, @LinguList and @xrotwang ? I am assigning it to myself, at least for now.

**Comment by LinguList** [comment]
Yes, guess this is just what we need!

**Comment by tresoldi** [comment]
This does not apply anymore, and the code has been moved to https://github.com/concepticon/pyconcepticon
