### ISSUE TITLE
Add test for duplicate concepts

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/concepticon-data#478]
A test for duplicate items in conceptlists would help prevent this [problem](https://github.com/clld/concepticon-data/pull/477)

**Comment by tresoldi** [comment]
Calling dibs, I can do it over the weekend or at most on Monday (just fixed something similar this morning).

**Comment by LinguList** [comment]
they are called "mergers", and you can find them listed in concepticon on github: https://github.com/clld/concepticon-data/blob/master/concepticondata/conceptlists/README.md

**Comment by LinguList** [comment]
we tolerate them, as we also have cases like "arrow 1", and "arrow 2" in cognate sets, where people reconstruct two proto-forms or so.

**Comment by xrotwang** [comment]
@LinguList That page also still lists 126 concepts - so it seems to be stale. I guess @SimonGreenhill didn't run `concepticon stats` before making the PR. (He possibly didn't even know about this :) )

**Comment by LinguList** [comment]
yes:

```
$ concepticon stats
``` 
should fix this, @SimonGreenhill :)

**Comment by SimonGreenhill** [comment]
No, didn't know about it, but doing it now.

**Comment by LinguList** [comment]
do we have this documented in our contributing.md ?

**Comment by LinguList** [comment]
hand-json was what I did last time this occured.

BTW: https://github.com/clld/concepticon-data/blob/master/CONTRIBUTING.md#checklist-for-pull-requests

We mention it on contributing.md, but we probably need some "how I added my first concept list" tutorial @MacyL is working on this with help by @tresoldi, we actually have our seminar on concepticon next week Tuesday 14 pm!

**Comment by xrotwang** [comment]
A tool that needs a university seminar for introduction sounds scary :)

**Comment by LinguList** [comment]
it's for newcomers, wouldnt' put that label "university seminar" too high ;) 

But we should also be clear that it is not always as straightforward as it seems and that doing these things in some consistent way is by no means something one learns in half an hour by watching a youtube video (at least judging from all PRs I have criticized so far, probably annoying contributors...)

**Comment by tresoldi** [comment]
BTW, the handout for the session is here: [https://github.com/digling/calc-seminar/blob/master/handouts/Session_3.ipynb](https://github.com/digling/calc-seminar/blob/master/handouts/Session_3.ipynb)

**Comment by SimonGreenhill** [comment]
Ok, closing this then.
