### ISSUE TITLE
[Question] Name changes for some concepts

### ISSUE THREAD

**Issue by Schweikhard** [clld/concepticon-data#497]
I'd like to rename some concepts, but since this means renaming them in all linked files I would like to first ask for approval before going ahead with it.
I have in mind the following concepts:

FUR to PELT
GOD to DEITY
CAUSE TO (LET) to CAUSE TO OR PERMIT
VEGETABLE KNIFE to KITCHEN KNIFE
BROKEN to NOT WORKING (and then the concept SHATTERED which I added to BROKEN)

**Comment by LinguList** [comment]
Please propose the definitions as well. I am skeptical above PELT, as the FUR is more common, referring to animal hair covering the body of mammals. One lists may need to be linked to a new concept set "pelt", as referring to the fur of an animal used for clothing, although this concept (Pelz in German) is also ambiguous in Russian, etc.

God deity is possible, is the term use as an address? (similar to "mama" vs. "mother"?) This needs re-checking i all lists, leaving "god" as the prototypical deity in Leibniz and other lists (at least, there I don't see a reason for this "deity"). Ideally, keep god but add deity as new concept set and relink those lists where you see it fits. 

Vegetable knife is just a vegetable knife in one list, no need to change. The translation is literal, unless @MacyL or @laiyunfan confirm that this IS a kitchen knife (which would also be used for cutting meat). 

Broken is only ill-defined, so changing the definition into "shattered into pieces" will solve all problems there, as all other lists MEAN exactly this (at least most of them, and it's just a few of them.

**Comment by Schweikhard** [comment]
FUR currently contains mostly concepts where it's not clear whether their refer to animal body hair or pelt. Some clearly refer to pelt, only one clearly refers to animal body hair. I guess we might best move the clear ones to new subconcepts and leave the ambiguous ones at the current concept.

Deity seems like the more neutral term. Tim pointed out that polytheists might not associate the term god with their deities. We don't have a concept list yet that only uses the term deity (Sun uses "god/deity").

Knife for preparing food is also in 2 other lists, but they are only linked to kitchen knife on my fork as far. I asked @MacyL about it earlier and she confirmed that what is currently linked to vegetable knife is a kitchen knife in general.

Regarding broken, 2 refer to not-working, the 2 Chinese ones mean literally broken as far as I remember, Key contains both meanings and the rest (Backstrom's and yours) don't provide information on the website.
Perhaps here again leaving the ambiguous ones where they are and move the clear ones to sub-concepts?

**Comment by LinguList** [comment]
Leave the concepts in fur where it is not clear and add a pelt, if you feel this is needed.

Leave "God" for Leibniz and the ancient lists, as they refer to the western god, and add the deity, where we'd also have to relink Sun etc.

Link to kitchen knife as you proposed.

Rename broken into "broken (not working)", and move concepts accordingly. "not working" itself is not a good concept gloss. the usage of brackets is helpful for specification. Even better: leave broken, and add sub-concepts, as you maybe even suggestedin your last statement.

**Comment by Schweikhard** [comment]
Okay, will do so!
