### ISSUE TITLE
Chinese glosses of Sun 1991 1004 not showing

### ISSUE THREAD

**Issue by Schweikhard** [clld/concepticon-data#498]
For most multilingual concept lists, data of all elicitation languages is listed on Concepticon both on the overview of the list itself
e.g. http://concepticon.clld.org/contributions/Key-2016-1310
and on the pages of concept sets the list is linked to
e.g. http://concepticon.clld.org/parameters/1852

This however is not the case for Sun 1991 1004.
(see http://concepticon.clld.org/contributions/Sun-1991-1004
and e.g. http://concepticon.clld.org/parameters/1732)
The only way to access its Chinese glosses is by going to the specific page of that concept:
e.g. http://concepticon.clld.org/values/Sun-1991-1004-1

**Comment by LinguList** [comment]
"Chinese" was missing in conceptlists.tsv, if you don't name it there, it won't show up.

**Comment by LinguList** [comment]
see [here](https://github.com/clld/concepticon-data/commit/c1e844a4347b6a3fa25743854893549dd5b3f162) for the diff

**Comment by Schweikhard** [comment]
Thanks. I figured it was something like that but I didn't know which file to edit for it.
