### ISSUE TITLE
Reinhard-1970 linked as "Kusunda-1972"

### ISSUE THREAD

**Issue by Schweikhard** [clld/concepticon-data#502]
https://concepticon.clld.org/contributions/Reinhard-1970-337
Where can this be corrected?

**Comment by LinguList** [comment]
annoying thing, these mappings, as we haven't a test for this.The way to go is to add the new ids into "retired.json" here: https://github.com/clld/concepticon-data/blob/master/concepticondata/retired.json, so you change the name, but if you click on an older ID, it will be re-directed. In principle, this should also be done with all name changes, to guarantee backwards compatibility, etc., but we haven't had a precedent for this so far, or do you have a suggestion how to proceed here, @xrotwang ? (I mean: not for Kusunda, but for changed gloss names).

**Comment by xrotwang** [comment]
What exactly is the question?
The general idea is to be able to track any ID for any object in concepticon that has ever been assigned. Unfortunately, this info isn't used yet in the web app (see https://github.com/clld/concepticon/issues/32), but in theory a URL like
https://concepticon.clld.org/values/Galicio-2015-100-1
should be redirected appropriately.

So in this case, it seems as if the individual concept URLs would need to be re-assigned, right? I.e.
https://concepticon.clld.org/values/Kusunda-1972-337-1
should redirect to
https://concepticon.clld.org/values/Kusunda-1970-337-1
Is this correct? If so, yes, re-assign and add the old IDs (and their new correct replacements) to `retired.json`.

**Comment by LinguList** [comment]
Yes!

The bigger problem is probably the renaming of Concepticon Glosses. If we completely change one Concepticon Gloss with a definition and the mapping that is attached to a Concepticon ID, we may easily loose backwards compatibility. On the other hand, I'd also say that, similar to Glottolog, where a language name of a given glottocode may be retired, as it is shown that this assignment was wrong, this name is changed with a newer version, right? At the moment, we don't loose anything, but the many renamings of Concepticon Glosses introduced by @Schweikhard may lead to confusion if we check with the linking of, for example, datasets in lexibank. So what I try to say: it is probably okay for this PR, but we might want to think of a policy across releases: Re-linking elicitation glosses in concept lists is something that always needs to be done, but retiring or renaming a gloss completely, e.g., replacing "apple" by "cidre" should be avoided. This seems to be more in the responsibility of us, who curate the data, but it would be useful to keep it in mind.

**Comment by xrotwang** [comment]
I think the issue about the IDs has been resolved. The issue about changing glosses of concept sets as well - at least theoretically. As discussed with @LinguList , recycling of conceptset IDs **must not** happen. So if a concept set turns out to be inappropriate for whatever reason, we'll retire the ID - and never reassign it again.
