### ISSUE TITLE
Swadesh 100 list as emoji

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#509]
* https://www.superlinguo.com/post/177670651002/the-swadesh-100-list-as-emoji

**Comment by tresoldi** [comment]
As I wrote in email, the list seems to be still under development, given both comments on the blog post and on the related Google Sheet. Also, many of the new suggestions refer to the next Unicode release.

Should we join the discussion? Should we add the list as it is? Should we wait?

**Comment by SimonGreenhill** [comment]
Probably not a high priority, and given that it's not an official publication, how about we close this until it's either finished or published?
