### ISSUE TITLE
Protected branches, DevOps, DataOps & Co.

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#512]
As @Anaphory mentioned [here](https://github.com/lingpy/lingpy/issues/376) (and @tresoldi and @xrotwang discussed someplace else, I just can't remember where exactly), protecting branches of our workhorse-packages (`pyconcepticon` within and including `concepticon-data`, `pyglottolog`, `lingpy`, etc.) might be something we should pursue further.

- This supports the good practice of submitting changes in the form of pull requests (which we're doing anyway, but it *actively* supports it and prevents mishaps).
- Additionally, we might use this to engage in further (minor) good DevOp & DataOp practices
  - always have reviewers for PRs
  - push data updates and code updates to different, dedicated branches (imo very useful for a repository like this one, where data and code co-exist)

GitHub nicely supports [this](https://help.github.com/articles/defining-the-mergeability-of-pull-requests/). Any opinions?

**Comment by xrotwang** [comment]
Yes, I had a discussion about this with @d97hah he felt that imposing this workflow, and not allowing users to choose between fas-track minor changes and full PRs was quite a hindrance. So `clld/glottolog` will not opt into such a scheme now. But I'm open to do this for other packages :)

**Comment by xrotwang** [comment]
@tresoldi Yes, the branch-protection feature would prevent any direct pushes to the `master` branch. Optionally this can be extended to also require one approving review.

**Comment by chrzyki** [comment]
Yep, essentially, we're very flexible how much we want to implement and enforce.

@xrotwang I understand that sentiment. For some cases/projects it might just not be a good fit. :)

**Comment by chrzyki** [comment]
So, a proposal:

Code repositories get, per default, the following two branches:
- `master`, self-explanatory; branches get merged into this and releases are based on the `master` branch. The master branch is protected.
- `devel`, changes & commits go into this branch, get merged after a positive review. I'm personally a strong proponent of going this route even for minor changes, but this is certainly open for discussion and might make more or less sense for certain repositories. Make strong use of squashing commits for merging.

Additionally, major rewrites/features/projects might result in additional branches (e.g. `lingpy3` comes to mind). These branches should be properly named and documented (e.g. in the form of issues, READMEs, or GitHub projects) so that their purpose and aim is clear. As such, I'd also like to clean up very of the stalled branches across our repositories.

For repositories that share data and code I'd suggest an additional branch `data` that can be used for working on, well, the repositorie's data. This makes working on code & data at the same time cleaner and should, per definition of the branches, not result in any conflicts.

**Comment by xrotwang** [comment]
I'm in favor of enforcing PR + review for all (even minor) changes. For most codebases we have more than one core developer, now, so this should be feasible. I don't like the long-lived, shared `devel` branch, though. I'd leave it to each developer's decision, in which branch (and in which fork for that matter) they'd wish to work. With a shared, long-lived branch it is unclear which state it is supposed to be in, and there's always the risc of it becoming stale, at which point we'd have to redefine the workflow.

**Comment by chrzyki** [comment]
Thanks & I agree!

**Comment by chrzyki** [comment]
No immediate urgency for now I take it. Closing this and will revisit later.
