### ISSUE TITLE
New concepts needed for spring/summer and autumn/winter

### ISSUE THREAD

**Issue by brianave** [clld/concepticon-data#514]
I'm cleaning up an automatically mapped list and I came across the glosses "spring/summer" and "autumn/winter".  HOT SEASON might be OK for "spring/summer" but I'm not sure it's exactly the same, and there isn't anything like "cold season" that could correspond to "autumn/winter."

**Comment by LinguList** [comment]
if you don't find an exact-exact match, leave it open and think of proposing a new concept along with your linked list to our project (you'll be given full credits), just follow the guide-lines and make a PR. Don't go for near-good matches or similar, as this is against our basic principle, rather leave things unlinked (it's anyway unlikely than that you'll find a good gloss for spring/summer in another concept list).
