### ISSUE TITLE
Test for conceptlist TAGS coming from a controlled list

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#52]
The `TAGS` specified for concept lists in `conceptlists.tsv` should come from a controlled list as specified in the [README.md](https://github.com/clld/concepticon-data/blob/master/README.md#note-on-concept-list-types).

**Comment by LinguList** [comment]
Agree, should I quickly set up such a list? The current tags have been modified since I last mentioned them in the readme...

**Comment by xrotwang** [comment]
This is the status quo:
```python
CL_TYPES = {
    "acquisition",
    "annotated",
    "areal",
    "basic",
    "hihi",
    "historical",
    "lolo",
    "proto-language",
    "questionnaire",
    "ranked",
    "sign language",
    "specific",
    "stable",
    "ultra-stable",
    "unstable",
}
```

**Comment by LinguList** [comment]
Allright, should I write up an explanation regarding the tags, or should we just leave it as is? If I add new lists in the future and I add new tags, I'll update the list. But where should it "reside"?

**Comment by xrotwang** [comment]
We can leave it as is right now, and maybe turn it into a dict later, where you give an explanation (possibly using markdown) as value. So I'd say we put it in `concepticondata/data.py` as well, and maybe create a README.md from it in the future, too.

**Comment by LinguList** [comment]
Yep, good idea!
