### ISSUE TITLE
Expand description of Alpher-and-Nash-1999

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#525]
Maybe the description of [Alpher 1999](https://concepticon.clld.org/contributions/Alpher-1999-151) should be expanded to include the [Appendix to Alpher and Nash 1999](http://www.anu.edu.au/linguistics/nash/aust/wl.html):

> The first 100 words constitute the list of O'Grady and Klokeid (1969:303-7); the next 20 are the words in Hale's (1961) list that are not also in O'Grady and Klokeid's; the next 25 are words in Black's (nd a.) list that are not in either of the above; the last 6 words (relevant for the most part in the monsoon tropics of Australia) are the authors' additions.

**Comment by LinguList** [comment]
I was annoyed at some point because I failed to track down the older studies  the list is based upon (e.g., Black's list that is not known). But yes, mentioning all this is probably useful.
