### ISSUE TITLE
Swadesh-1964-215: Russian translation list

### ISSUE THREAD

**Issue by natalia-morozova** [clld/concepticon-data#530]
Dear all,

While going through the Russian translation list of Swadesh's list of 215 concepts, I have noticed several typos.

Here's the link to the list: 
[https://concepticon.clld.org/contributions/Swadesh-1964-215](url)

The typos I've found:

ID                                   | LANGUAGE | INCORRECT  => CORRECT
Swadesh-1964-215-1     (English)         *alle => *all
Swadesh-1964-215-47   (Russian)       падатз => падать
Swadesh-1964-215-89   (Russian)       званть => знать
Swadesh-1964-215-91   (Russian)       смеаться => смеяться
Swadesh-1964-215-102 (Russian)       мьсо => мясо
Swadesh-1964-215-106 (Russian)       имь => имя
Swadesh-1964-215-108 (Russian)       блиский  => близкий
Swadesh-1964-215-110 (Russian)       новы  => новый
Swadesh-1964-215-164 (Russian)       звесда  => звезда
Swadesh-1964-215-212 (Russian)       червьк => червяк

**Comment by LinguList** [comment]
Thanks, can you change them in the document? The typos are typical for some German typing fast a phonetic keyboard for Russian (i.e., me), so very glad if you correct them.

**Comment by LinguList** [comment]
Very good, just for the next time, I'd suggest that you make a PR (@chrzyki will tell you what this is), so we can quickly have a look at the changes. But I just looked at them, and of course they are all fine. A problem can only appear if the changes break the code (what was not the case here), so these should run through our check and be reviewed by our little community...

**Comment by LinguList** [comment]
BTW: there are more Russian lists, and some may also need checking, as it was usually me who typed them off (but be aware that some pre-date the 1900+-x spelling reform, so the writing is different).

**Comment by chrzyki** [comment]
The not-PR or rather editing the files directly is on me, sorry. :) Told @natalia-morozova that this ok this once until we've got her computer completely rather (still waiting on software, ugh) and she can do PRs properly.

**Comment by LinguList** [comment]
No problem, this is perfectly fine then, and I support your decision, was just worried that the distinction between editing directly and PR is not clear, so glad to see you already thought of this.

**Comment by natalia-morozova** [comment]
Sorry, didn't know that, thanks for the information! 

I also wanted to ask you about the reference information. I am working on another Russian translation list from the same source (Новое в Лингвистике. Выпуск 1), so I have noticed that the actual date of publication was 1960 (https://classes.ru/grammar/148.new-in-linguistics-1/source/worddocuments/1.htm). Is there a reason why the date of publication was changed and if I should stick to the year of 1964 for the other list?

**Comment by LinguList** [comment]
So the date I gave for Swadesh in the version is also wrong? Yes, just checked also [here](http://www.philology.ru/linguistics1/swadesh-60.htm). So we have to modify this.

**Comment by LinguList** [comment]
See #531, as this is not trivial to change, but use the corrected date, please in new lists to be added.

**Comment by LinguList** [comment]
> Sorry, didn't know that, thanks for the information!

No need to apologize, @chrzyki was right in asking you to directly change this time.

**Comment by LinguList** [comment]
Ah, @natalia-morozova: to avoid typing, you may look for the books in this website phylology.ru, I mentioned above. They have a digitized version.
