### ISSUE TITLE
Swadesh-1964-215: modify date

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#531]
The date should be 1960. This needs to be done with a backward-compatibility, by adding a javascript file with changes. @chrzyki, do you know how to do this? If not, leave open until I have time.

**Comment by chrzyki** [comment]
Yeah I can do that. I would also like to do that together with @natalia-morozova on Monday. Is it okay if we let it sit until then?

**Comment by LinguList** [comment]
Sure, this is not urgent, I'd say.

**Comment by LinguList** [comment]
Where are we on this?
