### ISSUE TITLE
wrong linking in He's list

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#549]
https://concepticon.clld.org/values/He-2010-207-166

should be linked to the "earth-ball".

**Comment by LinguList** [comment]
EARTH WET SUBSTANCE is also identical with EARTH SOIL

**Comment by Schweikhard** [comment]
So EARTH (WET SUBSTANCE) should be retired?
Its ID is higher than that of EARTH (SOIL), can I still put the latter's ID into the former's last column to retire it?

**Comment by LinguList** [comment]
Earth wet substance is higher than earth soil, so if you add earth soil's ID to the last column, you'll retire it. The other way would go against the practice.

**Comment by Schweikhard** [comment]
Thanks - should I also mark it as sameas in conceprelations, or is that redundant?

**Comment by LinguList** [comment]
I think it's redundant, we started with sameas, and later added the alias, to retire concepts, so it won't be needed.
