### ISSUE TITLE
PLAIT/BRAID/WEAVE

### ISSUE THREAD

**Issue by Schweikhard** [clld/concepticon-data#550]
The concept 1729 PLAIT OR BRAID OR WEAVE is currently not used as a hyponym entry although it looks like one.

Some related entries:
WEAVE is about creating a cloth by interlacing threads.
PLAIT is a noun, the result of making intentional folds in cloth, also called a pleat.
BRAID is a noun, the result of braiding hair (or of braiding together threads, strings etc.).

None of the entries on 1729 would fit any of those, though.
Buck refers to weaving a basket, which is also the definition 1729 has currently, but the other linked ones would all need new concepts: 
Borin: *LACE (VERB)
Bulakh/Kraft: *BRAID (VERB)
Haspelmath/Key/List: *WEAVE (BASKET) OR BRAID (VERB)

And I would also move Buck to a new concept *WEAVE (BASKET).

Definitions for the new concepts:
*LACE (VERB): To add decoration to a cloth by interlacing it with additional threads, thereby creating a pattern of gaps.
*BRAID (VERB) To braid together hair, threads, strings, twigs etc. in order to create a larger string-like object (which can be linear as in a braid of hair or circular as in a wreath).
*WEAVE (BASKET): To weave a basket or use similar techniques for creating other objects.
*WEAVE (BASKET) OR BRAID (VERB): Hyponym of those two.

This would mean discontinuing 1729 for now, as its name fits neither of the meanings. It could be used as a hyponym of several of the concepts, once we find a concept list that combines them in one concept.

If that's fine I would go ahead with that.

Additionally, there are several entries on PLAIT that refer to BRAID which I would then fix as well.

**Comment by tresoldi** [comment]
As per our oral discussion, I agree with that.

**Comment by Schweikhard** [comment]
Updated the linkings and added the missing concepts.
Linked Borin to the same as Key etc., though, as its definition is really difficult to understand:
to weave or plait/braid: "make by braiding or interlacing; &quot;lace a tablecloth&quot;"
and as it's supposed to be based on Key.
