### ISSUE TITLE
EARTH WET SUBSTANCE is identical with EARTH SOIL

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#552]
Or what is the difference?

**Comment by Schweikhard** [comment]
I would guess in Wheeler2015, the former is MUD, the latter is EARTH (SOIL).
地球 in He2010 would be EARTH (SOIL) I assume?

**Comment by LinguList** [comment]
He is "Erdkugel" ...

**Comment by Schweikhard** [comment]
Then it should be linked to GLOBE?
https://concepticon.clld.org/parameters/2588
