### ISSUE TITLE
Incorrect mappings, ontological categories, and a typo

### ISSUE THREAD

**Issue by natalia-morozova** [clld/concepticon-data#553]
I have noticed some issues while working with Concepticon, hopefully, it will be helpful:

- Incorrect mapping:

|  CONCEPTLIST  |  ID  |  CONCEPT  |  GLOSS  |  CORRECT MAPPING  |
| ----- | ----- | ----- | ----- | ----- |
| [Buck 1949 1108](https://concepticon.clld.org/contributions/Buck-1949-1108)  | [Buck-1949-1108-514](https://concepticon.clld.org/values/Buck-1949-1108-514) | 294 TUMPLINE | become [english]  | 1990 BECOME  |
| [Buck 1949 1108](https://concepticon.clld.org/contributions/Buck-1949-1108)  | [Buck-1949-1108-275](https://concepticon.clld.org/values/Buck-1949-1108-275)  | 1378 SPOON  | knife ( = table-knife) [english]  | 1352 KNIFE |
| [Borin 2012 40](https://concepticon.clld.org/contributions/Borin-2012-40) | [Borin-2012-40-20](https://concepticon.clld.org/values/Borin-2012-40-20) | 2430 OFFICE | marriage [english] | 2432 MARRIAGE |
| [Pallas 1786 441](https://concepticon.clld.org/contributions/Pallas-1786-441) | [Pallas-1786-441-351](https://concepticon.clld.org/values/Pallas-1786-441-351) | 1284 BANK | bank (noun); Banc [french]; Bank [german]; Scamnum [latin]; Скамья [russian] | 2584 BENCH |
| [Bulakh 2013 870](https://concepticon.clld.org/contributions/Bulakh-2013-870) | [Bulakh-2013-870-28](https://concepticon.clld.org/values/Bulakh-2013-870-28) | 218 FINE (PENALTY) | fine, powder-like [english] | 2157 FINE OR THIN |
| [Bulakh 2013 870](https://concepticon.clld.org/contributions/Bulakh-2013-870) | [Bulakh-2013-870-836](https://concepticon.clld.org/values/Bulakh-2013-870-836) | 344 TREE TRUNK | trunk (body part) [english] | 2667 TORSO |
| [Key 2016 1310](https://concepticon.clld.org/contributions/Key-2016-1310) | [Key-2016-1310-255](https://concepticon.clld.org/values/Key-2016-1310-255) | 765 MOVE | move [english]; mouvoir, bouger [french]; mover [portuguese]; двигаться [russian]; mover [spanish] | 2874 MOVE (ONESELF) |

The last issue with MOVE is tricky since it is not specified whether **move [english]** is transitive or intransitive, however, **двигаться [russian]** is definitely intransitive. 

- Typo:

| CONCEPT  | DEFINITION | CORRECTED |
| ------------- | ------------- | ------------- |
| 2245 BELCH | To release gas **fromt he** digestive tract through the mouth. | To release gas from the digestive tract through the mouth. |

Not sure about the issues with ontological categories, but please have a look at those:
- Incorrectly assigned ontological category

|  CONCEPT  |  ONTOLOGICAL CATEGORY  |  CORRECT  | COMMENT |
| ----- | ----- | ----- | ----- |
| 2758 CAREFUL | Person/Thing | Property |   |
| 2755 BUSY  | Person/Thing | Property |   |
| 1908 ATTENTIVE | Person/Thing | Property |   |
| 2376 HORIZONTAL | Person/Thing | Property | The definition seems to be ambiguous too  |
| 2531 BROAD  | Person/Thing | Property |   |

**Comment by LinguList** [comment]
> The last issue with MOVE is tricky since it is not specified whether move [english] is transitive or intransitive, however, двигаться [russian] is definitely intransitive.

This is okay, as all other languages are unspecified, and the general list was based on English, so leaving it unspecified is better, keeping in mind that the Russian gloss is incorrect, rather than our mapping.

As to the other issues: I agree with all of them. @chrzyki, it seems straightforward to include them, so could you maybe show @natalia-morozova how to make a pr here, or do it yourself?

**Comment by LinguList** [comment]
Ah, @chrzyki  is still sick. @natalia-morozova, do you know how to make a PR? If not, you could ask @Schweikhard, that he helps you, and you do that together?

**Comment by natalia-morozova** [comment]
Sure, I will ask Nathanael to explain to me how to do it.

**Comment by SimonGreenhill** [comment]
great work @natalia-morozova !
