### ISSUE TITLE
Definitions of HIT/BEAT/STRIKE, their hyperonym, and POUND

### ISSUE THREAD

**Issue by Schweikhard** [clld/concepticon-data#556]
Those 3 concepts and their hyperonym could likely need some better definitions but I'm very unsure how to distinguish/define them:
https://concepticon.clld.org/parameters/1433
https://concepticon.clld.org/parameters/1665
https://concepticon.clld.org/parameters/353
https://concepticon.clld.org/parameters/2133

Additionally, BEAT is also a hyponym of POUND
https://concepticon.clld.org/parameters/354

**Comment by tresoldi** [comment]
Just as an idea:

HIT - To forcefully or suddenly contacting one thing with another.
BEAT - To hit or strike repeatedly, usually in some sort of rhythm.
STRIKE - To hit against with a sharp blow or to impel, usually with a hand or weapon.
STRIKE OR BEAT - To hit or strike, either repeatedly or a single time.

**Comment by Schweikhard** [comment]
POUND seems to be: To crush rice using a giant mortar and pestle: https://gobackpacking.com/learning-to-pound-rice-in-the-philippines/
The few concepts linked to it that instead mean "pound with fists" could be linked either to STRIKE or to a new hyponym of that.

As the difference between HIT and STRIKE is kinda one of agency, how about:
HIT - To be forcefully or suddenly contacting, e.g. a tree falling down and hitting the ground.
