### ISSUE TITLE
Unlinked concepts & release preparations

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#568]
We've got the following 120 unlinked concepts in the to-be released data right now. Might be fruitful to revisit those before release.

| #   | Concept list              | Gloss     |
|-----|---------------------------|-----------|
| 1   | BeijingDaxue-1964-905-259 | courtyard |
| 2   | BeijingDaxue-1964-905-265 | desk      |
| 3   | BeijingDaxue-1964-905-268 | box       |
| 4   | BeijingDaxue-1964-905-377 | swing     |
| 5   | BeijingDaxue-1964-905-480 | dust      |
| 6   | BeijingDaxue-1964-905-537 | pull      |
| 7   | BeijingDaxue-1964-905-541 | hug       |
| 8   | BeijingDaxue-1964-905-548 | cover     |
| 9   | BeijingDaxue-1964-905-595 | cut       |
| 10  | BeijingDaxue-1964-905-607 | mix       |
| 11  | BeijingDaxue-1964-905-653 | shiver    |
| 12  | BeijingDaxue-1964-905-711 | straight  |
| 13  | BeijingDaxue-1964-905-732 | old       |
| 14  | BeijingDaxue-1964-905-822 | these     |
| 15  | BeijingDaxue-1964-905-823 | those     |
| 16  | BeijingDaxue-1964-905-880 | most      |
| 17  | BeijingDaxue-1964-905-884 | all       |
| 18  | BeijingDaxue-1964-905-887 | again     |
| 19  | BeijingDaxue-1964-905-892 | certainly |
| 20  | BeijingDaxue-1964-905-894 | not       |
| 21  | Borin-2012-40-32          | source    |
| 22  | Bowern-2012-644-299       | later     |
| 23  | Bowern-2017-348-56        | bottom    |
| 24  | Bromley-1967-111-39       | I         |
| 25  | Buck-1949-1108-989        | count     |
| 26  | Buck-1949-1108-1106       | spirit    |
| 27  | Calero-2002-15-11         | Muzzle    |
| 28  | Castro-2015-608-93        | young     |
| 29  | Castro-2015-608-404       | to        |
| 30  | Dellert-2017-1016-86      | drop      |
| 31  | Dellert-2017-1016-216     | wish      |
| 32  | Dellert-2017-1016-217     | desire    |
| 33  | Dellert-2017-1016-243     | people    |
| 34  | Dellert-2017-1016-250     | help      |
| 35  | Dellert-2017-1016-253     | matter    |
| 36  | Dellert-2017-1016-286     | row       |
| 37  | Dellert-2017-1016-349     | dish      |
| 38  | Dellert-2017-1016-351     | corn      |
| 39  | Dellert-2017-1016-389     | scarf     |
| 40  | Dellert-2017-1016-401     | pasture   |
| 41  | Dellert-2017-1016-438     | fight     |
| 42  | Dellert-2017-1016-586     | long      |
| 43  | Dellert-2017-1016-589     | later     |
| 44  | Dellert-2017-1016-615     | below     |
| 45  | Dellert-2017-1016-632     | under     |
| 46  | Dellert-2017-1016-683     | begin     |
| 47  | Dellert-2017-1016-686     | rise      |
| 48  | Dellert-2017-1016-717     | shine     |
| 49  | Dellert-2017-1016-742     | wake      |
| 50  | Dellert-2017-1016-743     | get       |
| 51  | Dellert-2017-1016-775     | depart    |
| 52  | Dellert-2017-1016-778     | enter     |
| 53  | Dellert-2017-1016-783     | wait      |
| 54  | Dellert-2017-1016-809     | show      |
| 55  | Dellert-2017-1016-810     | hear      |
| 56  | Dellert-2017-1016-817     | stop      |
| 57  | Dellert-2017-1016-823     | place     |
| 58  | Dellert-2017-1016-831     | leave     |
| 59  | Dellert-2017-1016-841     | bow       |
| 60  | Dellert-2017-1016-843     | spin      |
| 61  | Dellert-2017-1016-858     | stick     |
| 62  | Dellert-2017-1016-879     | grab      |
| 63  | Dellert-2017-1016-885     | get       |
| 64  | Dellert-2017-1016-899     | hand      |
| 65  | Dellert-2017-1016-902     | wish      |
| 66  | Dellert-2017-1016-906     | cover     |
| 67  | Dellert-2017-1016-925     | leave     |
| 68  | Dellert-2017-1016-951     | catch     |
| 69  | Dellert-2017-1016-958     | water     |
| 70  | Dellert-2017-1016-973     | sweep     |
| 71  | Dellert-2017-1016-975     | wash      |
| 72  | Dellert-2017-1016-1008    | draw      |
| 73  | Dolch-1936-220-4          | but       |
| 74  | Dolch-1936-220-18         | over      |
| 75  | Dolch-1936-220-68         | out       |
| 76  | Dolch-1936-220-87         | *best     |
| 77  | Dolch-1936-220-88         | *better   |
| 78  | Dolch-1936-220-97         | every     |
| 79  | Dolch-1936-220-113        | *own      |
| 80  | Dolch-1936-220-175        | let       |
| 81  | Dolch-1936-220-181        | may       |
| 82  | Dolch-1936-220-186        | please    |
| 83  | Heggarty-2014-110-13      | bath      |
| 84  | Heggarty-2014-110-19      | better    |
| 85  | Huber-1992-374-250        | stream    |
| 86  | Huber-1992-374-322        | at        |
| 87  | Janhunan-2008-235-223     | one       |
| 88  | Kibrik-2012-122-19        | leave     |
| 89  | Kibrik-2012-122-41        | brush     |
| 90  | Kibrik-2012-122-46        | lock      |
| 91  | Kibrik-2012-122-54        | button    |
| 92  | Kibrik-2012-122-60        | roll      |
| 93  | Kibrik-2012-122-65        | stick     |
| 94  | Kibrik-2012-122-100       | wave      |
| 95  | Kibrik-2012-122-111       | hurt      |
| 96  | Kibrik-2012-122-112       | try       |
| 97  | Nicholas-1988-60-44       | Muzzle    |
| 98  | Ogden-1930-100-18         | will      |
| 99  | Ogden-1930-100-48         | every     |
| 100 | Ogden-1930-100-63         | but       |
| 101 | Ogden-1930-100-99         | please    |
| 102 | Ogden-1930-200-13         | bath      |
| 103 | Ogden-1930-200-133        | plane     |
| 104 | Sun-1991-1004-275         | gall      |
| 105 | Sun-1991-1004-433         | sieve     |
| 106 | Sun-1991-1004-579         | lean      |
| 107 | Sun-1991-1004-596         | rake      |
| 108 | Sun-1991-1004-658         | open      |
| 109 | Sun-1991-1004-718         | weep      |
| 110 | Sun-1991-1004-777         | tremble   |
| 111 | Sun-1991-1004-791         | wither    |
| 112 | Sun-1991-1004-811         | thick     |
| 113 | Sun-1991-1004-1004        | don't     |
| 114 | Tryon-1983-324-128        | headland  |
| 115 | Woll-2010-301-30          | but       |
| 116 | Zgraggen-1980-380-156     | cane      |
| 117 | Zgraggen-1980-380-198a    | axe       |
| 118 | Zgraggen-1980-380-381     | you       |
| 119 | Zgraggen-1980-380-397     | his       |
| 120 | Zgraggen-1980-380-409     | them      |

**Comment by xrotwang** [comment]
@Schweikhard @LinguList @SimonGreenhill any takers? I think most of these have been not linked for a while - and @chrzyki thinks what the API proposes is wrong in most cases.

**Comment by SimonGreenhill** [comment]
I think a lot of these are more specific terms that aren't in concepticon e.g. Bromley-111-39 is "I heard" (not "I" -- is this splitting on space?) e.g. https://github.com/clld/concepticon-data/blob/master/concepticondata/conceptlists/Bromley-1967-111.tsv#L40

**Comment by xrotwang** [comment]
I remember I had a first pass through these when I implemented the `notlinked` command. So I'd be ok with leaving all of them as they are now for 2.0 as well.

**Comment by SimonGreenhill** [comment]
added a few more in [Z'graggen](https://github.com/clld/concepticon-data/commit/9971e661fccc0cfc7d5dd8a8ee7ac82837f86bf9). Would be good to get someone to go through all the pronouns in the datasets at some point (we're missing lots of duals and plurals)

**Comment by Schweikhard** [comment]
I have the impression much in this list is either intentionally unlinked or would necessitate the adding of new concepts (some quite reasonable, though, like HELP (NOUN)). Some also point to potential mislinkings of other lists.

Seems like a good idea to go through the whole list still. I could take care of all except the Chinese ones (BeijingDaxue and Sun I think).

**Comment by Schweikhard** [comment]
So, went through all of the list above, except for Beijing and Sun (Chinese) and Kibrik (Russian). Only fixed what didn't necessitate new concepts.

**Comment by chrzyki** [comment]
Thank you!
