### ISSUE TITLE
Links outdated http://language.psy.auckland.ac.nz/bantu/

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon-data#586]
See here: https://concepticon.clld.org/values/TeilDautrey-2008-430-35

Need to be updated to https://abvd.shh.mpg.de/bantu/word.php?v=35 etc. Might be an issue for other lists as well.

Coincidentally, 'beer banana' might be my favourite concept of the day.

**Comment by SimonGreenhill** [comment]
Anything on language.psy.auckland.ac.nz/* has gone to abvd.shh.mpg.de/*

**Comment by chrzyki** [comment]
Closed in #588.
