### ISSUE TITLE
Rename concept lists from Bennett

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#595]
The three concept lists attributed to Patrick Bennett have the wrong last name in the ID: It's `Bennett`, not `Bennet`.

**Comment by xrotwang** [comment]
@LinguList we should probably roll this into 2.0, right?

**Comment by LinguList** [comment]
Yes, I'm afraid. Later, we may forget about it, and get reluctanct of doing it. Today, everybody is in "Aufräumstimmung". Any takers on this?

**Comment by xrotwang** [comment]
I'll do it.
