### ISSUE TITLE
Handling identical or almost identical lists across multiple publications

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#61]
Following up from the discussion in the [PR #58](https://github.com/clld/concepticon-data/pull/58), I thought it was useful to turn this into an issue.

It seems that with the lists by Shirō Hattori, we have an excellent example for identical concept lists across different publications. There is still the question of how to handle it. A simple solution would be to list several references, and indicate in the note-column of conceptlists.tsv which additional data-point stems from which list (suppose a list which had only English, but has added Japanese in a later identical edition). This is feasible, since there are not too many lists, where this needs to be done. Another possibility of what we could think would be to add yet another column to conceptlists.tsv which might be called USEDBY or something similar, indicating whether this very list was used in further publications. The list by Dyen et al. 1992/1997 would be a usecase for this, since it is exactly identical with the list by Swadesh-1952-200, but they use uppercase where Swadesh used normal orthography. If we, otherwise keep on following a policy by which we say that theoretically, no two lists are the same (and one can fight about this), this would mean that Dyen 1992 should also be added, and Hattori's lists should be split into three or four.

We basically have a small problem of ontology and epistemology already now in the concepticon, since it is clear that we cannot just trust the papers if they say they used the list by Swadesh, for example, since they often use new concept labels, but claim they are based on some list. So it might be the most coherent way to add all lists we can get, but this may then turn out to be redundant, so the "ALSO-USED-By" (or whatever better label) may be a compromise solution. 

But I'm by no means completely convinced by either of the solutions mentioned above...

**Comment by xrotwang** [comment]
Currently I'd lean to "add them all". Mostly because figuring out identity is already an analysis, something we want to be able to do with our data. This alternative makes it also easier to stick to our "labels as given in source" policy.

**Comment by LinguList** [comment]
Allright, this seems to be the cleanest solution, I agree. And, even the work load may be considered as less grave, since the decision of which lists we include next is mainly up to us. So we can delay adding Dyen 1992 or all list of Hattori, until we find time to do this. So ideally, we add them all, but the priority are for the moment lists to be included in LexiBank, but also list interesting for those who want to do the linking, and this gives me enough freedom to ignore certain lists for the moment...

**Comment by LinguList** [comment]
I'll close this issue then, since we have all we need to account for this already, and no further things need to be done. There are even already lists which are almost or completely identical in our sample.
