### ISSUE TITLE
Missing russian source concepts

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon-data#8]
The following three concept lists list Russian as source language, but do not have a corresponding column RUSSIAN:

- Starostin-1991-110
- Jachontov-1991-100
- Jachontov-1991-65

**Comment by xrotwang** [comment]
@LinguList how should we procede with this issue? I think there should always be a correspondence between source languages listed in `conceptlists.tsv` and columns in the concept list, so that I can use the metadata to lookup the values in the concept list. This is particularly important because we allow arbitrary additional columns in the concept lists, so that a misspelled column, e.g. `RUSSAN` would be hard to detect.

So this would leave us with three options:

1. Remove the languages we have no data for from  `conceptlists.tsv`.
2. Add empty columns for these languages to the concept lists.
3. Add the columns and the data to the concept lists.

Obviously, option 3 would be the best. How feasible do you think it is?

**Comment by LinguList** [comment]
I prefer 3. I'll try to see to have it done ASAP! From a linguistic viewpoint, the Russian source concepts are very important information (also for tracing specific problems in the actual lists). I was just too lazy to type them off, so this is on me...

**Comment by xrotwang** [comment]
For Norman-2003-40 we have the opposite problem: There is a CHINESE column in the concept list, but Chinese is not listed as source language. Should I just add it?

**Comment by LinguList** [comment]
Yes, please. This is an error in the metadata.

**Comment by xrotwang** [comment]
@LinguList  Ok, so I'll implement option 2 and you can then fill in the data.

**Comment by LinguList** [comment]
super, this keeps the workflow going and I'll have some time to cope
with the errors (I'll try to correct them quickly, though)...
