### ISSUE TITLE
Add information for potential contributors, introducing the workflow, etc.

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon-data#95]
Basically, we can do this via the github, and we do not need to have it done when submitting the final version of the lrec paper, and it is also related to #66, since we could do this all in a rush, showing how to map via github in a readme file, showing how to contribute new stuff, and linking this relevant part of the repository to the website, rather than having it on the website itself.

**Comment by xrotwang** [comment]
Should be done in a documnent [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) in the repos.

**Comment by LinguList** [comment]
Allright, this seems to be pretty straightforward, thanks!

**Comment by LinguList** [comment]
Closing this for the moment, since I just added to "contributing.md". This is of course not complete, but we should first see whether there are actually people who want to contribute. If it turns out to be really interesting to more than just one geek, we should expand it.
